import streamlit as st

bilesikler = [
    {'simgesi': 'H', 'mol agir': 1.0, 'adi': 'HİDROJEN'},
    {'simgesi': 'He', 'mol agir': 4.0, 'adi': 'HELYUM'},
    {'simgesi': 'Li', 'mol agir': 7.0, 'adi': 'LİTYUM'},
    {'simgesi': 'Be', 'mol agir': 9.0, 'adi': 'BERİLYUM'},
    {'simgesi': 'B', 'mol agir': 11.0, 'adi': 'BOR'},
    {'simgesi': 'C', 'mol agir': 12.0, 'adi': 'KARBON'},
    {'simgesi': 'N', 'mol agir': 14.0, 'adi': 'AZOT'},
    {'simgesi': 'O', 'mol agir': 16.0, 'adi': 'OKSİJEN'},
    {'simgesi': 'F', 'mol agir': 19.0, 'adi': 'FLOR'},
    {'simgesi': 'Ne', 'mol agir': 20.0, 'adi': 'NEON'},
    {'simgesi': 'Na', 'mol agir': 23.0, 'adi': 'SODYUM'},
    {'simgesi': 'Mg', 'mol agir': 24.0, 'adi': 'MAGNEZYUM'},
    {'simgesi': 'Al', 'mol agir': 27.0, 'adi': 'ALÜMİNYUM'},
    {'simgesi': 'Si', 'mol agir': 28.0, 'adi': 'SİLİSYUM'},
    {'simgesi': 'P', 'mol agir': 31.0, 'adi': 'FOSFOR'},
    {'simgesi': 'S', 'mol agir': 32.0, 'adi': 'KÜKÜRT'},
    {'simgesi': 'Cl', 'mol agir': 35.5, 'adi': 'KLOR'},
    {'simgesi': 'Ar', 'mol agir': 40.0, 'adi': 'ARGON'},
    {'simgesi': 'K', 'mol agir': 39.0, 'adi': 'POTASYUM'},
    {'simgesi': 'Ca', 'mol agir': 40.0, 'adi': 'KALSİYUM'},
    {'simgesi': 'Sc', 'mol agir': 45.0, 'adi': 'SKANDİYUM'},
    {'simgesi': 'Ti', 'mol agir': 48.0, 'adi': 'TİTAN'},
    {'simgesi': 'V', 'mol agir': 51.0, 'adi': 'VANADYUM'},
    {'simgesi': 'Cr', 'mol agir': 52.0, 'adi': 'KROM'},
    {'simgesi': 'Mn', 'mol agir': 55.0, 'adi': 'MANGAN'},
    {'simgesi': 'Fe', 'mol agir': 56.0, 'adi': 'DEMİR'},
    {'simgesi': 'Co', 'mol agir': 59.0, 'adi': 'KOBALT'},
    {'simgesi': 'Ni', 'mol agir': 58.0, 'adi': 'NİKEL'},
    {'simgesi': 'Cu', 'mol agir': 63.5, 'adi': 'BAKIR'},
    {'simgesi': 'Zn', 'mol agir': 65.0, 'adi': 'ÇİNKO'},
    {'simgesi': 'Ga', 'mol agir': 70.0, 'adi': 'GALYUM'},
    {'simgesi': 'Ge', 'mol agir': 73.0, 'adi': 'GERMANYUM'},
    {'simgesi': 'As', 'mol agir': 75.0, 'adi': 'ARSENİK'},
    {'simgesi': 'Se', 'mol agir': 79.0, 'adi': 'SELENYUM'},
    {'simgesi': 'Br', 'mol agir': 80.0, 'adi': 'BROM'},
    {'simgesi': 'Kr', 'mol agir': 84.0, 'adi': 'KRİPTON'},
    {'simgesi': 'Rb', 'mol agir': 85.0, 'adi': 'RUBİDYUM'},
    {'simgesi': 'Sr', 'mol agir': 88.0, 'adi': 'STRONSİYUM'},
    {'simgesi': 'Y', 'mol agir': 89.0, 'adi': 'YTRİYUM'},
    {'simgesi': 'Zr', 'mol agir': 91.0, 'adi': 'ZİRKONYUM'},
    {'simgesi': 'Nb', 'mol agir': 93.0, 'adi': 'NİYOBYUM'},
    {'simgesi': 'Mo', 'mol agir': 96.0, 'adi': 'MOLİBDEN'},
    {'simgesi': 'Tc', 'mol agir': 98.0, 'adi': 'TEKNESYUM'},
    {'simgesi': 'Ru', 'mol agir': 101.0, 'adi': 'RUTENYUM'},
    {'simgesi': 'Rh', 'mol agir': 103.0, 'adi': 'RODYUM'},
    {'simgesi': 'Pd', 'mol agir': 106.0, 'adi': 'PALLADYUM'},
    {'simgesi': 'Ag', 'mol agir': 108.0, 'adi': 'GÜMÜŞ'},
    {'simgesi': 'Cd', 'mol agir': 112.0, 'adi': 'KADMİYUM'},
    {'simgesi': 'In', 'mol agir': 115.0, 'adi': 'İNDİYUM'},
    {'simgesi': 'Sn', 'mol agir': 119.0, 'adi': 'KALAY'},
    {'simgesi': 'Sb', 'mol agir': 121.0, 'adi': 'ANTİMON'},
    {'simgesi': 'Te', 'mol agir': 127.0, 'adi': 'TELLÜR'},
    {'simgesi': 'I', 'mol agir': 127.0, 'adi': 'İYOT'},
    {'simgesi': 'Xe', 'mol agir': 131.0, 'adi': 'XSENON'},
    {'simgesi': 'Cs', 'mol agir': 133.0, 'adi': 'SEZYUM'},
    {'simgesi': 'Ba', 'mol agir': 137.0, 'adi': 'BARYUM'},
    {'simgesi': 'La', 'mol agir': 139.0, 'adi': 'LANTAN'},
    {'simgesi': 'Ce', 'mol agir': 140.0, 'adi': 'SERYUM '},
    {'simgesi': 'Pr', 'mol agir': 141.0, 'adi': 'PRASEODİM'},
    {'simgesi': 'Nd', 'mol agir': 144.0, 'adi': 'NEODİM'},
    {'simgesi': 'Pm', 'mol agir': 145.0, 'adi': 'PROMETYUM'},
    {'simgesi': 'Sm', 'mol agir': 150.0, 'adi': 'SAMARYUM'},
    {'simgesi': 'Eu', 'mol agir': 152.0, 'adi': 'EUROPYUM'},
    {'simgesi': 'Gd', 'mol agir': 157.0, 'adi': 'GADOLİNYUM'},
    {'simgesi': 'Tb', 'mol agir': 159.0, 'adi': 'TERBİYUM'},
    {'simgesi': 'Dy', 'mol agir': 162.0, 'adi': 'DİSPROSYUM'},
    {'simgesi': 'Ho', 'mol agir': 165.0, 'adi': 'HOLMİYUM'},
    {'simgesi': 'Er', 'mol agir': 167.0, 'adi': 'ERBİYUM'},
    {'simgesi': 'Tm', 'mol agir': 169.0, 'adi': 'TULYUM'},
    {'simgesi': 'Yb', 'mol agir': 173.0, 'adi': 'YTTERBİYUM'},
    {'simgesi': 'Lu', 'mol agir': 175.0, 'adi': 'LUTESYUM'},
    {'simgesi': 'Hf', 'mol agir': 178.0, 'adi': 'HAFNİYUM'},
    {'simgesi': 'Ta', 'mol agir': 181.0, 'adi': 'TALYUM'},
    {'simgesi': 'W', 'mol agir': 184.0, 'adi': 'WOLFRAM'},
    {'simgesi': 'Re', 'mol agir': 186.0, 'adi': 'RENYUM'},
    {'simgesi': 'Os', 'mol agir': 190.0, 'adi': 'OSMİYUM'},
    {'simgesi': 'Ir', 'mol agir': 192.0, 'adi': 'IRRIDYUM'},
    {'simgesi': 'Pt', 'mol agir': 195.0, 'adi': 'PLATİN'},
    {'simgesi': 'Au', 'mol agir': 197.0, 'adi': 'ALTIN'},
    {'simgesi': 'Hg', 'mol agir': 200.0, 'adi': 'CIVA'},
    {'simgesi': 'Tl', 'mol agir': 204.0, 'adi': 'TALYUM'},
    {'simgesi': 'Pb', 'mol agir': 207.0, 'adi': 'KURŞUN'},
    {'simgesi': 'Bi', 'mol agir': 209.0, 'adi': 'BİZMUT'},
    {'simgesi': 'Po', 'mol agir': 209.0, 'adi': 'POLONYUM'},
    {'simgesi': 'At', 'mol agir': 210.0, 'adi': 'ASTATİN'},
    {'simgesi': 'Rn', 'mol agir': 222.0, 'adi': 'RADON'},
    {'simgesi': 'Fr', 'mol agir': 223.0, 'adi': 'FRANSİYUM'},
    {'simgesi': 'Ra', 'mol agir': 226.0, 'adi': 'RADYUM'},
    {'simgesi': 'Ac', 'mol agir': 227.0, 'adi': 'AKTİNYUM'},
    {'simgesi': 'Th', 'mol agir': 232.0, 'adi': 'TORYUM'},
    {'simgesi': 'Pa', 'mol agir': 231.0, 'adi': 'PROTAKTİNYUM'},
    {'simgesi': 'U', 'mol agir': 238.0, 'adi': 'URANYUM'},
    {'simgesi': 'Np', 'mol agir': 237.0, 'adi': 'NEPTÜNYUM'},
    {'simgesi': 'Pu', 'mol agir': 244.0, 'adi': 'PLÜTONYUM'},
    {'simgesi': 'Am', 'mol agir': 243.0, 'adi': 'AMERİKYUM'},
    {'simgesi': 'Cm', 'mol agir': 247.0, 'adi': 'KÜRYUM'},
    {'simgesi': 'Bk', 'mol agir': 247.0, 'adi': 'BERKELYUM'},
    {'simgesi': 'Cf', 'mol agir': 251.0, 'adi': 'KALİFORNİYUM'},
    {'simgesi': 'Es', 'mol agir': 252.0, 'adi': 'ANŞTAYNYUM'},
    {'simgesi': 'Fm', 'mol agir': 257.0, 'adi': 'FERMİYUM'},
    {'simgesi': 'Md', 'mol agir': 258.0, 'adi': 'MENDELEVYUM'},
    {'simgesi': 'No', 'mol agir': 259.0, 'adi': 'NOBELYUM'},
    {'simgesi': 'Lr', 'mol agir': 260.0, 'adi': 'LAWRENSİYUM'},
    {'simgesi': 'Rf', 'mol agir': 261.0, 'adi': 'RADIRFORDİYUM'},
    {'simgesi': 'Db', 'mol agir': 262.0, 'adi': 'DUBNİYUM'},
    {'simgesi': 'Sg', 'mol agir': 263.0, 'adi': 'SEABORGİYUM'},
    {'simgesi': 'Bh', 'mol agir': 262.0, 'adi': 'BOHRYUM'},
    {'simgesi': 'Hs', 'mol agir': 265.0, 'adi': 'HASSİYUM'},
    {'simgesi': 'Mt', 'mol agir': 266.0, 'adi': 'MAYTNERYUM'},
    {'simgesi': 'Ds', 'mol agir': 271.0, 'adi': 'DARMSTADTİYUM'},
    {'simgesi': 'Rg', 'mol agir': 272.0, 'adi': 'RÖNGENYUM'},
    {'simgesi': 'Cn', 'mol agir': 277.0, 'adi': 'KOPERNİKYUM'},
    {'simgesi': 'Nh', 'mol agir': 284.0, 'adi': 'NİHONYUM'},
    {'simgesi': 'Fl', 'mol agir': 289.0, 'adi': 'FLEROVYUM'},
    {'simgesi': 'Mc', 'mol agir': 288.0, 'adi': 'MOKOVYUM'},
    {'simgesi': 'Lv', 'mol agir': 292.0, 'adi': 'LİVERMORYUM'},
    {'simgesi': 'Ts', 'mol agir': 294.0, 'adi': 'TENNESSİN'},
    {'simgesi': 'Og', 'mol agir': 294.0, 'adi': 'OGANESSON'},
    {'simgesi': 'HC', 'mol agir': 13.0, 'adi': 'BİKARBON'},
    {'simgesi': 'H2', 'mol agir': 2.0, 'adi': 'HİDROJEN MOLEKÜLÜ'},
    {'simgesi': 'LiH', 'mol agir': 8.0, 'adi': 'LİTYUM HİDRÜR'},
    {'simgesi': 'NaH', 'mol agir': 24.0, 'adi': 'SODYUM HİDRÜR'},
    {'simgesi': 'KH', 'mol agir': 40.0, 'adi': 'POTASYUM HİDRÜR'},
    {'simgesi': 'AgH', 'mol agir': 109.0, 'adi': 'GÜMÜŞ HİDRÜR'},
    {'simgesi': 'MgH2', 'mol agir': 26.0, 'adi': 'MAGNEZYUM HİDRÜR'},
    {'simgesi': 'CaH2', 'mol agir': 42.0, 'adi': 'KALSİYUM HİDRÜR'},
    {'simgesi': 'SrH2', 'mol agir': 89.0, 'adi': 'STRONSİYUM HİDRÜR'},
    {'simgesi': 'BaH2', 'mol agir': 139.0, 'adi': 'BARYUM HİDRÜR'},
    {'simgesi': 'ZnH2', 'mol agir': 67.0, 'adi': 'ÇİNKO HİDRÜR'},
    {'simgesi': 'AlH3', 'mol agir': 30.0, 'adi': 'ALÜMİNYUM HİDRÜR'},
    {'simgesi': 'HF', 'mol agir': 20.0, 'adi': 'HİDROFLORİK ASİT/CAM ASİTİ'},
    {'simgesi': 'HCl', 'mol agir': 36.5, 'adi': 'HİDROKLORİK ASİT/TUZ RUHU'},
    {'simgesi': 'HBr', 'mol agir': 81.0, 'adi': 'HİDROBROMİK ASİT'},
    {'simgesi': 'HI', 'mol agir': 128.0, 'adi': 'HİDROİYODİK ASİT'},
    {'simgesi': 'H2O', 'mol agir': 18.0, 'adi': 'DİHİDROJEN MONOKSİT/SU'},
    {'simgesi': 'H2S', 'mol agir': 34.0, 'adi': 'HİDROJEN SÜLFÜR/ÇÜRÜK YUMURTA KOKUSU'},
    {'simgesi': 'BH3', 'mol agir': 14.0, 'adi': 'BOROHİDRÜR/BOR TRİHİDRÜR'},
    {'simgesi': 'NH3', 'mol agir': 17.0, 'adi': 'AMONYAK'},
    {'simgesi': 'H3P', 'mol agir': 34.0, 'adi': 'HİDROJEN FOSFÜR'},
    {'simgesi': 'CH4', 'mol agir': 16.0, 'adi': 'METAN'},
    {'simgesi': 'F2', 'mol agir': 38.0, 'adi': 'FLOR MOLEKÜLÜ'},
    {'simgesi': 'ClF', 'mol agir': 54.5, 'adi': 'KLOR FLORÜR'},
    {'simgesi': 'BrF', 'mol agir': 109.0, 'adi': 'BROM FLORÜR'},
    {'simgesi': 'IF', 'mol agir': 146.0, 'adi': 'İYOT FLORÜR'},
    {'simgesi': 'OF2', 'mol agir': 54.0, 'adi': 'OKSİJEN DİFLORÜR'},
    {'simgesi': 'SF2', 'mol agir': 70.0, 'adi': 'KÜKÜRT DİFLORÜR'},
    {'simgesi': 'SF4', 'mol agir': 108.0, 'adi': 'KÜKÜRT TRİFLORÜR'},
    {'simgesi': 'SF6', 'mol agir': 146.0, 'adi': 'KÜKÜRT HEKSAFLORÜR'},
    {'simgesi': 'BF3', 'mol agir': 68.0, 'adi': 'BOR TRİFLORÜR'},
    {'simgesi': 'NF3', 'mol agir': 71.0, 'adi': 'AZOT TRİFLORÜR'},
    {'simgesi': 'NF5', 'mol agir': 109.0, 'adi': 'AZOT PENTAFLORÜR'},
    {'simgesi': 'PF3', 'mol agir': 88.0, 'adi': 'FOSFOR TRİFLORÜR'},
    {'simgesi': 'PF5', 'mol agir': 126.0, 'adi': 'FOSFOR PENTAFLORÜR'},
    {'simgesi': 'CF4', 'mol agir': 88.0, 'adi': 'KARBON TETRAFLORÜR'},
    {'simgesi': 'LİF', 'mol agir': 26.0, 'adi': 'LİTYUM FLORÜR'},
    {'simgesi': 'NaF', 'mol agir': 42.0, 'adi': 'SODYUM FLORÜR'},
    {'simgesi': 'KF', 'mol agir': 58.0, 'adi': 'POTASYUM FLORÜR'},
    {'simgesi': 'AgF', 'mol agir': 147.0, 'adi': 'GÜMÜŞ FLORÜR'},
    {'simgesi': 'NH4F', 'mol agir': 37.0, 'adi': 'AMONYUM FLORÜR'},
    {'simgesi': 'MgF2', 'mol agir': 62.0, 'adi': 'MAGNEZYUM FLORÜR'},
    {'simgesi': 'CaF2', 'mol agir': 78.0, 'adi': 'KALSİYUM FLORÜR'},
    {'simgesi': 'SrF2', 'mol agir': 126.0, 'adi': 'STRONSİYUM FLORÜR'},
    {'simgesi': 'BaF2', 'mol agir': 175.0, 'adi': 'BARYUM FLORÜR'},
    {'simgesi': 'ZnF2', 'mol agir': 103.0, 'adi': 'ÇİNKO FLORÜR'},
    {'simgesi': 'AlF3', 'mol agir': 84.0, 'adi': 'ALÜMİNYUM FLORÜR'},
    {'simgesi': 'CuF', 'mol agir': 82.5, 'adi': 'BAKIR I FLORÜR'},
    {'simgesi': 'CuF2', 'mol agir': 101.5, 'adi': 'BAKIR II FLORÜR'},
    {'simgesi': 'HgF', 'mol agir': 219.0, 'adi': 'CIVA I FLORÜR'},
    {'simgesi': 'HgF2', 'mol agir': 238.0, 'adi': 'CIVA II FLORÜR'},
    {'simgesi': 'FeF2', 'mol agir': 94.0, 'adi': 'DEMİR II FLORÜR'},
    {'simgesi': 'FeF3', 'mol agir': 113.0, 'adi': 'DEMİR III FLORÜR'},
    {'simgesi': 'MnF2', 'mol agir': 93.0, 'adi': 'MANGAN II FLORÜR'},
    {'simgesi': 'MnF4', 'mol agir': 131.0, 'adi': 'MANGAN IV FLORÜR'},
    {'simgesi': 'SnF2', 'mol agir': 157.0, 'adi': 'KALAY II FLORÜR'},
    {'simgesi': 'SnF4', 'mol agir': 195.0, 'adi': 'KALAY IV FLORÜR'},
    {'simgesi': 'PbF2', 'mol agir': 245.0, 'adi': 'KURŞUN II FLORÜR'},
    {'simgesi': 'PbF4', 'mol agir': 283.0, 'adi': 'KURŞUN IV FLORÜR'},
    {'simgesi': 'Cl2', 'mol agir': 71.0, 'adi': 'KLOR MOLEKÜLÜ'},
    {'simgesi': 'BrCl', 'mol agir': 115.5, 'adi': 'BROM KLORÜR'},
    {'simgesi': 'ICl', 'mol agir': 162.5, 'adi': 'İYOT KLORÜR'},
    {'simgesi': 'Cl2O', 'mol agir': 87.0, 'adi': 'DİKLOR MONOKSİT'},
    {'simgesi': 'SCl2', 'mol agir': 103.0, 'adi': 'KÜKÜRT DİKLORÜR'},
    {'simgesi': 'SCl4', 'mol agir': 141.0, 'adi': 'KÜKÜRT TRİKLORÜR'},
    {'simgesi': 'SCl6', 'mol agir': 245.0, 'adi': 'KÜKÜRT HEKSAKLORÜR'},
    {'simgesi': 'BCl3', 'mol agir': 117.5, 'adi': 'BOR TRİKLORÜR'},
    {'simgesi': 'NCl3', 'mol agir': 120.5, 'adi': 'AZOT TRİKLORÜR'},
    {'simgesi': 'NCl5', 'mol agir': 158.5, 'adi': 'AZOT PENTAKLORÜR'},
    {'simgesi': 'PCl3', 'mol agir': 137.5, 'adi': 'FOSFOR TRİKLORÜR'},
    {'simgesi': 'PCl5', 'mol agir': 175.5, 'adi': 'FOSFOR PENTAKLORÜR'},
    {'simgesi': 'CCl4', 'mol agir': 154.0, 'adi': 'KARBON TETRAKLORÜR'},
    {'simgesi': 'LİCl', 'mol agir': 42.5, 'adi': 'LİTYUM KLORÜR'},
    {'simgesi': 'NaCl', 'mol agir': 58.5, 'adi': 'SODYUM KLORÜR/YEMEK TUZU/TUZ'},
    {'simgesi': 'KCl', 'mol agir': 74.5, 'adi': 'POTASYUM KLORÜR'},
    {'simgesi': 'AgCl', 'mol agir': 143.5, 'adi': 'GÜMÜŞ KLORÜR'},
    {'simgesi': 'NH4Cl', 'mol agir': 53.5, 'adi': 'AMONYUM KLORÜR'},
    {'simgesi': 'MgCl2', 'mol agir': 95.0, 'adi': 'MAGNEZYUM KLORÜR'},
    {'simgesi': 'CaCl2', 'mol agir': 111.0, 'adi': 'KALSİYUM KLORÜR'},
    {'simgesi': 'SrCl2', 'mol agir': 159.0, 'adi': 'STRONSİYUM KLORÜR'},
    {'simgesi': 'BaCl2', 'mol agir': 208.0, 'adi': 'BARYUM KLORÜR'},
    {'simgesi': 'ZnCl2', 'mol agir': 136.0, 'adi': 'ÇİNKO KLORÜR'},
    {'simgesi': 'AlCl3', 'mol agir': 133.5, 'adi': 'ALÜMİNYUM KLORÜR'},
    {'simgesi': 'CuCl', 'mol agir': 99.0, 'adi': 'BAKIR I KLORÜR'},
    {'simgesi': 'CuCl2', 'mol agir': 134.5, 'adi': 'BAKIR II KLORÜR'},
    {'simgesi': 'HgCl', 'mol agir': 235.5, 'adi': 'CIVA I KLORÜR'},
    {'simgesi': 'HgCl2', 'mol agir': 271.0, 'adi': 'CIVA II KLORÜR'},
    {'simgesi': 'FeCl2', 'mol agir': 127.0, 'adi': 'DEMİR II KLORÜR'},
    {'simgesi': 'FeCl3', 'mol agir': 162.5, 'adi': 'DEMİR III KLORÜR'},
    {'simgesi': 'MnCl2', 'mol agir': 126.0, 'adi': 'MANGAN II KLORÜR'},
    {'simgesi': 'MnCl4', 'mol agir': 197.0, 'adi': 'MANGAN IV KLORÜR'},
    {'simgesi': 'SnCl2', 'mol agir': 190.0, 'adi': 'KALAY II KLORÜR'},
    {'simgesi': 'SnCl4', 'mol agir': 228.0, 'adi': 'KALAY IV KLORÜR'},
    {'simgesi': 'PbCl2', 'mol agir': 278.0, 'adi': 'KURŞUN II KLORÜR'},
    {'simgesi': 'PbCl4', 'mol agir': 349.0, 'adi': 'KURŞUN IV KLORÜR'},
    {'simgesi': 'I2', 'mol agir': 254.0, 'adi': 'İYOT MOLEKÜLÜ'},
    {'simgesi': 'I2O', 'mol agir': 270.0, 'adi': 'DİİYOT MONOKSİT'},
    {'simgesi': 'SI2', 'mol agir': 286.0, 'adi': 'KÜKÜRT DİİYODÜR'},
    {'simgesi': 'SI4', 'mol agir': 540.0, 'adi': 'KÜKÜRT TRİİYODÜR'},
    {'simgesi': 'SI6', 'mol agir': 794.0, 'adi': 'KÜKÜRT HEKSAİYODÜR'},
    {'simgesi': 'BI3', 'mol agir': 392.0, 'adi': 'BOR TRİİYODÜR'},
    {'simgesi': 'NI3', 'mol agir': 395.0, 'adi': 'AZOT TRİİYODÜR'},
    {'simgesi': 'NI5', 'mol agir': 649.0, 'adi': 'AZOT PENTAİYODÜR'},
    {'simgesi': 'PI3', 'mol agir': 412.0, 'adi': 'FOSFOR TRİİYODÜR'},
    {'simgesi': 'PI5', 'mol agir': 666.0, 'adi': 'FOSFOR PENTAİYODÜR'},
    {'simgesi': 'CI4', 'mol agir': 520.0, 'adi': 'KARBON TETRAİYODÜR'},
    {'simgesi': 'LiI', 'mol agir': 134.0, 'adi': 'LİTYUM İYODÜR'},
    {'simgesi': 'NaI', 'mol agir': 150.0, 'adi': 'SODYUM İYODÜR'},
    {'simgesi': 'KI', 'mol agir': 166.0, 'adi': 'POTASYUM İYODÜR'},
    {'simgesi': 'AgI', 'mol agir': 235.0, 'adi': 'GÜMÜŞ İYODÜR'},
    {'simgesi': 'NH4I', 'mol agir': 145.0, 'adi': 'AMONYUM İYODÜR'},
    {'simgesi': 'MgI2', 'mol agir': 278.0, 'adi': 'MAGNEZYUM İYODÜR'},
    {'simgesi': 'CaI2', 'mol agir': 294.0, 'adi': 'KALSİYUM İYODÜR'},
    {'simgesi': 'SrI2', 'mol agir': 342.0, 'adi': 'STRONSİYUM İYODÜR'},
    {'simgesi': 'BaI2', 'mol agir': 391.0, 'adi': 'BARYUM İYODÜR'},
    {'simgesi': 'ZnI2', 'mol agir': 319.0, 'adi': 'ÇİNKO İYODÜR'},
    {'simgesi': 'AlI3', 'mol agir': 408.0, 'adi': 'ALÜMİNYUM İYODÜR'},
    {'simgesi': 'CuI', 'mol agir': 190.5, 'adi': 'BAKIR I İYODÜR'},
    {'simgesi': 'CuI2', 'mol agir': 317.5, 'adi': 'BAKIR II İYODÜR'},
    {'simgesi': 'HgI', 'mol agir': 327.0, 'adi': 'CIVA I İYODÜR'},
    {'simgesi': 'HgI2', 'mol agir': 454.0, 'adi': 'CIVA II İYODÜR'},
    {'simgesi': 'FeI2', 'mol agir': 310.0, 'adi': 'DEMİR II İYODÜR'},
    {'simgesi': 'FeI3', 'mol agir': 437.0, 'adi': 'DEMİR III İYODÜR'},
    {'simgesi': 'MnI2', 'mol agir': 309.0, 'adi': 'MANGAN II İYODÜR'},
    {'simgesi': 'MnI4', 'mol agir': 563.0, 'adi': 'MANGAN IV İYODÜR'},
    {'simgesi': 'SnI2', 'mol agir': 373.0, 'adi': 'KALAY II İYODÜR'},
    {'simgesi': 'SnI4', 'mol agir': 627.0, 'adi': 'KALAY IV İYODÜR'},
    {'simgesi': 'PbI2', 'mol agir': 461.0, 'adi': 'KURŞUN II İYODÜR'},
    {'simgesi': 'PbI4', 'mol agir': 715.0, 'adi': 'KURŞUN IV İYODÜR'},
    {'simgesi': 'Br2', 'mol agir': 160.0, 'adi': 'BROM MOLEKÜLÜ'},
    {'simgesi': 'Br2O', 'mol agir': 176.0, 'adi': 'DİBROM MONOKSİT'},
    {'simgesi': 'SBr2', 'mol agir': 192.0, 'adi': 'KÜKÜRT DİBROMÜR'},
    {'simgesi': 'SBr4', 'mol agir': 352.0, 'adi': 'KÜKÜRT TRİBROMÜR'},
    {'simgesi': 'SBr6', 'mol agir': 512.0, 'adi': 'KÜKÜRT HEKSABROMÜR'},
    {'simgesi': 'BBr3', 'mol agir': 251.0, 'adi': 'BOR TRİBROMÜR'},
    {'simgesi': 'NBr3', 'mol agir': 254.0, 'adi': 'AZOT TRİBROMÜR'},
    {'simgesi': 'NBr5', 'mol agir': 414.0, 'adi': 'AZOT PENTABROMÜR'},
    {'simgesi': 'PBr3', 'mol agir': 271.0, 'adi': 'FOSFOR TRİBROMÜR'},
    {'simgesi': 'PBr5', 'mol agir': 431.0, 'adi': 'FOSFOR PENTABROMÜR'},
    {'simgesi': 'CBr4', 'mol agir': 332.0, 'adi': 'KARBON TETRABROMÜR'},
    {'simgesi': 'LiBr', 'mol agir': 87.0, 'adi': 'LİTYUM BROMÜR'},
    {'simgesi': 'NaBr', 'mol agir': 103.0, 'adi': 'SODYUM BROMÜR'},
    {'simgesi': 'KBr', 'mol agir': 119.0, 'adi': 'POTASYUM BROMÜR'},
    {'simgesi': 'AgBr', 'mol agir': 188.0, 'adi': 'GÜMÜŞ BROMÜR'},
    {'simgesi': 'NH4Br', 'mol agir': 98.0, 'adi': 'AMONYUM BROMÜR'},
    {'simgesi': 'MgBr2', 'mol agir': 184.0, 'adi': 'MAGNEZYUM BROMÜR'},
    {'simgesi': 'CaBr2', 'mol agir': 200.0, 'adi': 'KALSİYUM BROMÜR'},
    {'simgesi': 'SrBr2', 'mol agir': 268.0, 'adi': 'STRONSİYUM BROMÜR'},
    {'simgesi': 'BaBr2', 'mol agir': 297.0, 'adi': 'BARYUM BROMÜR'},
    {'simgesi': 'ZnBr2', 'mol agir': 225.0, 'adi': 'ÇİNKO BROMÜR'},
    {'simgesi': 'AlBr3', 'mol agir': 267.0, 'adi': 'ALÜMİNYUM BROMÜR'},
    {'simgesi': 'CuBr', 'mol agir': 143.5, 'adi': 'BAKIR I BROMÜR'},
    {'simgesi': 'CuBr2', 'mol agir': 223.5, 'adi': 'BAKIR II BROMÜR'},
    {'simgesi': 'HgBr', 'mol agir': 280.0, 'adi': 'CIVA I BROMÜR'},
    {'simgesi': 'HgBr2', 'mol agir': 360.0, 'adi': 'CIVA II BROMÜR'},
    {'simgesi': 'FeBr2', 'mol agir': 216.0, 'adi': 'DEMİR II BROMÜR'},
    {'simgesi': 'FeBr3', 'mol agir': 296.0, 'adi': 'DEMİR III BROMÜR'},
    {'simgesi': 'MnBr2', 'mol agir': 215.0, 'adi': 'MANGAN II BROMÜR'},
    {'simgesi': 'MnBr4', 'mol agir': 375.0, 'adi': 'MANGAN IV BROMÜR'},
    {'simgesi': 'SnBr2', 'mol agir': 279.0, 'adi': 'KALAY II BROMÜR'},
    {'simgesi': 'SnBr4', 'mol agir': 439.0, 'adi': 'KALAY IV BROMÜR'},
    {'simgesi': 'PbBr2', 'mol agir': 367.0, 'adi': 'KURŞUN II BROMÜR'},
    {'simgesi': 'PbBr4', 'mol agir': 527.0, 'adi': 'KURŞUN IV BROMÜR'},
    {'simgesi': 'O2', 'mol agir': 32.0, 'adi': 'OKSİJEN MOLEKÜLÜ'},
    {'simgesi': 'O3', 'mol agir': 48.0, 'adi': 'OZON MOLEKÜLÜ'},
    {'simgesi': 'SO2', 'mol agir': 64.0, 'adi': 'KÜKÜRT DİOKSİT'},
    {'simgesi': 'SO3', 'mol agir': 80.0, 'adi': 'KÜKÜRT TRİOKSİT'},
    {'simgesi': 'B2O3', 'mol agir': 70.0, 'adi': 'DİBOR TRİOKSİT'},
    {'simgesi': 'NO', 'mol agir': 30.0, 'adi': 'AZOT MONOKSİT'},
    {'simgesi': 'N2O', 'mol agir': 44.0, 'adi': 'DİZOT MONOKSİT/GÜLDÜRME GAZI'},
    {'simgesi': 'N2O3', 'mol agir': 76.0, 'adi': 'DİAZOT TRİOKSİT'},
    {'simgesi': 'N2O5', 'mol agir': 108.0, 'adi': 'DİAZOT PENTAOKSİT'},
    {'simgesi': 'P2O3', 'mol agir': 110.0, 'adi': 'DİFOSFOR TRİOKSİT'},
    {'simgesi': 'P2O5', 'mol agir': 142.0, 'adi': 'DİFOSFOR PENTAOKSİT'},
    {'simgesi': 'CO', 'mol agir': 28.0, 'adi': 'KARBON MONOKSİT'},
    {'simgesi': 'CO2', 'mol agir': 44.0, 'adi': 'KARBON DİOKSİT'},
    {'simgesi': 'Li2O', 'mol agir': 30.0, 'adi': 'LİTYUM OKSİT'},
    {'simgesi': 'Li2O2', 'mol agir': 46.0, 'adi': 'LİTYUM PEROKSİT'},
    {'simgesi': 'Na2O', 'mol agir': 62.0, 'adi': 'SODYUM OKSİT'},
    {'simgesi': 'Na2O2', 'mol agir': 78.0, 'adi': 'SODYUM PEROKSİT'},
    {'simgesi': 'Al2O3', 'mol agir': 102.0, 'adi': 'ALÜMİNYUM OKSİT'},
    {'simgesi': 'SiO2', 'mol agir': 60.0, 'adi': 'SİLİSYUM DİOKSİT'},
    {'simgesi': 'GeO2', 'mol agir': 104.0, 'adi': 'GERMANYUM OKSİT'},
    {'simgesi': 'K2O', 'mol agir': 94.0, 'adi': 'POTASYUM OKSİT'},
    {'simgesi': 'K2O2', 'mol agir': 110.0, 'adi': 'POTASYUM PEROKSİT'},
    {'simgesi': 'Ag2O', 'mol agir': 232.0, 'adi': 'GÜMÜŞ OKSİT'},
    {'simgesi': '(NH4)2O', 'mol agir': 44.0, 'adi': 'AMONYUM OKSİT'},
    {'simgesi': 'MgO', 'mol agir': 40.0, 'adi': 'MAGNEZYUM OKSİT'},
    {'simgesi': 'MgO2', 'mol agir': 56.0, 'adi': 'MAGNEZYUM PEROKSİT'},
    {'simgesi': 'CaO', 'mol agir': 56.0, 'adi': 'KALSİYUM OKSİT'},
    {'simgesi': 'CaO2', 'mol agir': 72.0, 'adi': 'KALSİYUM PEROKSİT'},
    {'simgesi': 'SrO', 'mol agir': 104.0, 'adi': 'STRONSİYUM OKSİT'},
    {'simgesi': 'SrO2', 'mol agir': 120.0, 'adi': 'STRONSİYUM PEROKSİT'},
    {'simgesi': 'BaO', 'mol agir': 153.0, 'adi': 'BARYUM OKSİT'},
    {'simgesi': 'BaO2', 'mol agir': 169.0, 'adi': 'BARYUM PEROKSİT'},
    {'simgesi': 'ZnO', 'mol agir': 81.0, 'adi': 'ÇİNKO OKSİT'},
    {'simgesi': 'Al2O3', 'mol agir': 102.0, 'adi': 'ALÜMİNYUM OKSİT'},
    {'simgesi': 'Cu2O', 'mol agir': 143.0, 'adi': 'BAKIR I OKSİT'},
    {'simgesi': 'CuO', 'mol agir': 79.5, 'adi': 'BAKIR II OKSİT'},
    {'simgesi': 'Hg2O', 'mol agir': 416.0, 'adi': 'CIVA I OKSİT'},
    {'simgesi': 'HgO', 'mol agir': 216.0, 'adi': 'CIVA II OKSİT'},
    {'simgesi': 'FeO', 'mol agir': 72.0, 'adi': 'DEMİR II OKSİT'},
    {'simgesi': 'Fe2O3', 'mol agir': 160.0, 'adi': 'DEMİR III OKSİT'},
    {'simgesi': 'MnO', 'mol agir': 71.0, 'adi': 'MANGAN II OKSİT'},
    {'simgesi': 'MnO2', 'mol agir': 87.0, 'adi': 'MANGAN IV OKSİT'},
    {'simgesi': 'Mn2O5', 'mol agir': 190.0, 'adi': 'MANGAN V OKSİT'},
    {'simgesi': 'Mn2O7', 'mol agir': 222.0, 'adi': 'MANGAN VII OKSİT'},
    {'simgesi': 'SnO', 'mol agir': 135.0, 'adi': 'KALAY II OKSİT'},
    {'simgesi': 'SnO2', 'mol agir': 151.0, 'adi': 'KALAY IV OKSİT'},
    {'simgesi': 'PbO', 'mol agir': 223.0, 'adi': 'KURŞUN II OKSİT'},
    {'simgesi': 'PbO2', 'mol agir': 239.0, 'adi': 'KURŞUN IV OKSİT'},
    {'simgesi': 'S4', 'mol agir': 128.0, 'adi': 'MONOKLİNİK KÜKÜRT'},
    {'simgesi': 'S8', 'mol agir': 256.0, 'adi': 'ROMBİK KÜKÜRT'},
    {'simgesi': 'B2S3', 'mol agir': 118.0, 'adi': 'DİBOR TRİSÜLFÜR'},
    {'simgesi': 'N2S3', 'mol agir': 124.0, 'adi': 'DİAZOT TRİSÜLFÜR'},
    {'simgesi': 'N2S5', 'mol agir': 188.0, 'adi': 'DİAZOT PENTASÜLFÜR'},
    {'simgesi': 'P2S3', 'mol agir': 158.0, 'adi': 'DİFOSFOR TRİSÜLFÜR'},
    {'simgesi': 'P2S5', 'mol agir': 222.0, 'adi': 'DİFOSFOR PENTASÜLFÜR'},
    {'simgesi': 'CS2', 'mol agir': 76.0, 'adi': 'KARBON DİSÜLFÜR'},
    {'simgesi': 'Li2S', 'mol agir': 46.0, 'adi': 'LİTYUM SÜLFÜR'},
    {'simgesi': 'Na2S', 'mol agir': 78.0, 'adi': 'SODYUM SÜLFÜR'},
    {'simgesi': 'K2S', 'mol agir': 110.0, 'adi': 'POTASYUM SÜLFÜR'},
    {'simgesi': 'Ag2S', 'mol agir': 248.0, 'adi': 'GÜMÜŞ SÜLFÜR'},
    {'simgesi': '(NH4)2S', 'mol agir': 68.0, 'adi': 'AMONYUM SÜLFÜR'},
    {'simgesi': 'MgS', 'mol agir': 56.0, 'adi': 'MAGNEZYUM SÜLFÜR'},
    {'simgesi': 'CaS', 'mol agir': 72.0, 'adi': 'KALSİYUM SÜLFÜR'},
    {'simgesi': 'SrS', 'mol agir': 120.0, 'adi': 'STRONSİYUM SÜLFÜR'},
    {'simgesi': 'BaS', 'mol agir': 169.0, 'adi': 'BARYUM SÜLFÜR'},
    {'simgesi': 'ZnS', 'mol agir': 97.0, 'adi': 'ÇİNKO SÜLFÜR'},
    {'simgesi': 'Al2S3', 'mol agir': 150.0, 'adi': 'ALÜMİNYUM SÜLFÜR'},
    {'simgesi': 'Cu2S', 'mol agir': 159.0, 'adi': 'BAKIR I SÜLFÜR'},
    {'simgesi': 'CuS', 'mol agir': 95.5, 'adi': 'BAKIR II SÜLFÜR'},
    {'simgesi': 'Hg2S', 'mol agir': 432.0, 'adi': 'CIVA I SÜLFÜR'},
    {'simgesi': 'HgS', 'mol agir': 232.0, 'adi': 'CIVA II SÜLFÜR'},
    {'simgesi': 'FeS', 'mol agir': 88.0, 'adi': 'DEMİR II SÜLFÜR'},
    {'simgesi': 'FeS2', 'mol agir': 120.0, 'adi': 'PİRİT'},
    {'simgesi': 'Fe2S3', 'mol agir': 208.0, 'adi': 'DEMİR III SÜLFÜR'},
    {'simgesi': 'MnS', 'mol agir': 87.0, 'adi': 'MANGAN II SÜLFÜR'},
    {'simgesi': 'MnS2', 'mol agir': 119.0, 'adi': 'MANGAN IV SÜLFÜR'},
    {'simgesi': 'Mn2S5', 'mol agir': 270.0, 'adi': 'MANGAN V SÜLFÜR'},
    {'simgesi': 'Mn2S7', 'mol agir': 334.0, 'adi': 'MANGAN VII SÜLFÜR'},
    {'simgesi': 'SnS', 'mol agir': 151.0, 'adi': 'KALAY II SÜLFÜR'},
    {'simgesi': 'SnS2', 'mol agir': 183.0, 'adi': 'KALAY IV SÜLFÜR'},
    {'simgesi': 'PbS', 'mol agir': 239.0, 'adi': 'KURŞUN II SÜLFÜR'},
    {'simgesi': 'PbS2', 'mol agir': 271.0, 'adi': 'KURŞUN IV SÜLFÜR'},
    {'simgesi': 'N2', 'mol agir': 28.0, 'adi': 'AZOT MOLEKÜLÜ'},
    {'simgesi': 'Li3N', 'mol agir': 35.0, 'adi': 'LİTYUM NİTRÜR'},
    {'simgesi': 'Na3N', 'mol agir': 83.0, 'adi': 'SODYUM NİTRÜR'},
    {'simgesi': 'K3N', 'mol agir': 131.0, 'adi': 'POTASYUM NİTRÜR'},
    {'simgesi': 'Ag3N', 'mol agir': 338.0, 'adi': 'GÜMÜŞ NİTRÜR'},
    {'simgesi': '(NH4)3N', 'mol agir': 56.0, 'adi': 'AMONYUM NİTRÜR'},
    {'simgesi': 'Be3N2', 'mol agir': 55.0, 'adi': 'BERİLYUM NİTRÜR'},
    {'simgesi': 'Mg3N2', 'mol agir': 100.0, 'adi': 'MAGNEZYUM NİTRÜR'},
    {'simgesi': 'Ca3N2', 'mol agir': 148.0, 'adi': 'KALSİYUM NİTRÜR'},
    {'simgesi': 'Sr3N2', 'mol agir': 292.0, 'adi': 'STRONSİYUM NİTRÜR'},
    {'simgesi': 'Ba3N2', 'mol agir': 439.0, 'adi': 'BARYUM NİTRÜR'},
    {'simgesi': 'Zn3N2', 'mol agir': 223.0, 'adi': 'ÇİNKO NİTRÜR'},
    {'simgesi': 'AlN', 'mol agir': 41.0, 'adi': 'ALÜMİNYUM NİTRÜR'},
    {'simgesi': 'Cu3N', 'mol agir': 204.5, 'adi': 'BAKIR I NİTRÜR'},
    {'simgesi': 'Cu3N2', 'mol agir': 218.5, 'adi': 'BAKIR II NİTRÜR'},
    {'simgesi': 'Hg3N', 'mol agir': 614.0, 'adi': 'CIVA I NİTRÜR'},
    {'simgesi': 'Hg3N2', 'mol agir': 628.0, 'adi': 'CIVA II NİTRÜR'},
    {'simgesi': 'Fe3N2', 'mol agir': 196.0, 'adi': 'DEMİR II NİTRÜR'},
    {'simgesi': 'FeN', 'mol agir': 70.0, 'adi': 'DEMİR III NİTRÜR'},
    {'simgesi': 'Mn3N2', 'mol agir': 193.0, 'adi': 'MANGAN II NİTRÜR'},
    {'simgesi': 'Mn3N4', 'mol agir': 221.0, 'adi': 'MANGAN IV NİTRÜR'},
    {'simgesi': 'Sn3N2', 'mol agir': 385.0, 'adi': 'KALAY II NİTRÜR'},
    {'simgesi': 'Sn3N4', 'mol agir': 413.0, 'adi': 'KALAY IV NİTRÜR'},
    {'simgesi': 'Pb3N2', 'mol agir': 649.0, 'adi': 'KURŞUN II NİTRÜR'},
    {'simgesi': 'Pb3N4', 'mol agir': 677.0, 'adi': 'KURŞUN IV NİTRÜR'},
    {'simgesi': 'P4', 'mol agir': 124.0, 'adi': 'BEYAZ FOSFOR MOLEKÜLÜ'},
    {'simgesi': 'Li3P', 'mol agir': 52.0, 'adi': 'LİTYUM FOSFÜR'},
    {'simgesi': 'Na3P', 'mol agir': 100.0, 'adi': 'SODYUM FOSFÜR'},
    {'simgesi': 'K3P', 'mol agir': 148.0, 'adi': 'POTASYUM FOSFÜR'},
    {'simgesi': 'Ag3P', 'mol agir': 355.0, 'adi': 'GÜMÜŞ FOSFÜR'},
    {'simgesi': '(NH4)3P', 'mol agir': 85.0, 'adi': 'AMONYUM FOSFÜR'},
    {'simgesi': 'Be3P2', 'mol agir': 89.0, 'adi': 'BERİLYUM FOSFÜR'},
    {'simgesi': 'Mg3P2', 'mol agir': 134.0, 'adi': 'MAGNEZYUM FOSFÜR'},
    {'simgesi': 'Ca3P2', 'mol agir': 182.0, 'adi': 'KALSİYUM FOSFÜR'},
    {'simgesi': 'Sr3P2', 'mol agir': 326.0, 'adi': 'STRONSİYUM FOSFÜR'},
    {'simgesi': 'Ba3P2', 'mol agir': 473.0, 'adi': 'BARYUM FOSFÜR'},
    {'simgesi': 'Zn3P2', 'mol agir': 257.0, 'adi': 'ÇİNKO FOSFÜR'},
    {'simgesi': 'AlP', 'mol agir': 58.0, 'adi': 'ALÜMİNYUM FOSFÜR'},
    {'simgesi': 'Cu3P', 'mol agir': 221.5, 'adi': 'BAKIR I FOSFÜR'},
    {'simgesi': 'Cu3P2', 'mol agir': 252.5, 'adi': 'BAKIR II FOSFÜR'},
    {'simgesi': 'Hg3P', 'mol agir': 631.0, 'adi': 'CIVA I FOSFÜR'},
    {'simgesi': 'Hg3P2', 'mol agir': 662.0, 'adi': 'CIVA II FOSFÜR'},
    {'simgesi': 'Fe3P2', 'mol agir': 230.0, 'adi': 'DEMİR II FOSFÜR'},
    {'simgesi': 'FeP', 'mol agir': 199.0, 'adi': 'DEMİR III FOSFÜR'},
    {'simgesi': 'Mn3P2', 'mol agir': 227.0, 'adi': 'MANGAN II FOSFÜR'},
    {'simgesi': 'Mn3P4', 'mol agir': 289.0, 'adi': 'MANGAN IV FOSFÜR'},
    {'simgesi': 'Sn3P2', 'mol agir': 331.0, 'adi': 'KALAY II FOSFÜR'},
    {'simgesi': 'Sn3P4', 'mol agir': 481.0, 'adi': 'KALAY IV FOSFÜR'},
    {'simgesi': 'Pb3P2', 'mol agir': 683.0, 'adi': 'KURŞUN II FOSFÜR'},
    {'simgesi': 'Pb3P4', 'mol agir': 745.0, 'adi': 'KURŞUN IV FOSFÜR'},
    {'simgesi': 'LiOH', 'mol agir': 24.0, 'adi': 'LİTYUM HİDROKSİT'},
    {'simgesi': 'NaOH', 'mol agir': 40.0, 'adi': 'SODYUM HİDROKSİT'},
    {'simgesi': 'KOH', 'mol agir': 56.0, 'adi': 'POTASYUM HİDROKSİT'},
    {'simgesi': 'AgOH', 'mol agir': 125.0, 'adi': 'GÜMÜŞ HİDROKSİT'},
    {'simgesi': 'NH4OH', 'mol agir': 35.0, 'adi': 'AMONYUM HİDROKSİT'},
    {'simgesi': 'Be(OH)2', 'mol agir': 43.0, 'adi': 'BERİLYUM HİDROKSİT'},
    {'simgesi': 'Mg(OH)2', 'mol agir': 58.0, 'adi': 'MAGNEZYUM HİDROKSİT'},
    {'simgesi': 'Ca(OH)2', 'mol agir': 74.0, 'adi': 'KALSİYUM HİDROKSİT'},
    {'simgesi': 'Sr(OH)2', 'mol agir': 122.0, 'adi': 'STRONSİYUM HİDROKSİT'},
    {'simgesi': 'Ba(OH)2', 'mol agir': 171.0, 'adi': 'BARYUM HİDROKSİT'},
    {'simgesi': 'Zn(OH)2', 'mol agir': 99.0, 'adi': 'ÇİNKO HİDROKSİT'},
    {'simgesi': 'Al(OH)3', 'mol agir': 78.0, 'adi': 'ALÜMİNYUM HİDROKSİT'},
    {'simgesi': 'CuOH', 'mol agir': 80.5, 'adi': 'BAKIR I HİDROKSİT'},
    {'simgesi': 'Cu(OH)2', 'mol agir': 97.5, 'adi': 'BAKIR II HİDROKSİT'},
    {'simgesi': 'HgOH', 'mol agir': 217.0, 'adi': 'CIVA I HİDROKSİT'},
    {'simgesi': 'Hg(OH)2', 'mol agir': 234.0, 'adi': 'CIVA II HİDROKSİT'},
    {'simgesi': 'Fe(OH)2', 'mol agir': 90.0, 'adi': 'DEMİR II HİDROKSİT'},
    {'simgesi': 'Fe(OH)3', 'mol agir': 107.0, 'adi': 'DEMİR III HİDROKSİT'},
    {'simgesi': 'Mn(OH)2', 'mol agir': 89.0, 'adi': 'MANGAN II HİDROKSİT'},
    {'simgesi': 'Mn(OH)4', 'mol agir': 123.0, 'adi': 'MANGAN IV HİDROKSİT'},
    {'simgesi': 'Sn(OH)2', 'mol agir': 153.0, 'adi': 'KALAY II HİDROKSİT'},
    {'simgesi': 'Sn(OH)4', 'mol agir': 187.0, 'adi': 'KALAY IV HİDROKSİT'},
    {'simgesi': 'Pb(OH)2', 'mol agir': 241.0, 'adi': 'KURŞUN II HİDROKSİT'},
    {'simgesi': 'Pb(OH)4', 'mol agir': 275.0, 'adi': 'KURŞUN IV HİDROKSİT'},
    {'simgesi': 'LiCN', 'mol agir': 33.0, 'adi': 'LİTYUM SİYANÜR'},
    {'simgesi': 'NaCN', 'mol agir': 49.0, 'adi': 'SODYUM SİYANÜR'},
    {'simgesi': 'KCN', 'mol agir': 65.0, 'adi': 'POTASYUM SİYANÜR'},
    {'simgesi': 'AgCN', 'mol agir': 134.0, 'adi': 'GÜMÜŞ SİYANÜR'},
    {'simgesi': 'NH4CN', 'mol agir': 44.0, 'adi': 'AMONYUM SİYANÜR'},
    {'simgesi': 'Be(CN)2', 'mol agir': 61.0, 'adi': 'BERİLYUM SİYANÜR'},
    {'simgesi': 'Mg(CN)2', 'mol agir': 76.0, 'adi': 'MAGNEZYUM SİYANÜR'},
    {'simgesi': 'Ca(CN)2', 'mol agir': 92.0, 'adi': 'KALSİYUM SİYANÜR'},
    {'simgesi': 'Sr(CN)2', 'mol agir': 140.0, 'adi': 'STRONSİYUM SİYANÜR'},
    {'simgesi': 'Ba(CN)2', 'mol agir': 189.0, 'adi': 'BARYUM SİYANÜR'},
    {'simgesi': 'Zn(CN)2', 'mol agir': 117.0, 'adi': 'ÇİNKO SİYANÜR'},
    {'simgesi': 'Al(CN)3', 'mol agir': 105.0, 'adi': 'ALÜMİNYUM SİYANÜR'},
    {'simgesi': 'CuCN', 'mol agir': 89.5, 'adi': 'BAKIR I SİYANÜR'},
    {'simgesi': 'Cu(CN)2', 'mol agir': 115.5, 'adi': 'BAKIR II SİYANÜR'},
    {'simgesi': 'HgCN', 'mol agir': 226.0, 'adi': 'CIVA I SİYANÜR'},
    {'simgesi': 'Hg(CN)2', 'mol agir': 252.0, 'adi': 'CIVA II SİYANÜR'},
    {'simgesi': 'Fe(CN)2', 'mol agir': 108.0, 'adi': 'DEMİR II SİYANÜR'},
    {'simgesi': 'Fe(CN)3', 'mol agir': 134.0, 'adi': 'DEMİR III SİYANÜR'},
    {'simgesi': 'Mn(CN)2', 'mol agir': 107.0, 'adi': 'MANGAN II SİYANÜR'},
    {'simgesi': 'Mn(CN)4', 'mol agir': 159.0, 'adi': 'MANGAN IV SİYANÜR'},
    {'simgesi': 'Sn(CN)2', 'mol agir': 171.0, 'adi': 'KALAY II SİYANÜR'},
    {'simgesi': 'Sn(CN)4', 'mol agir': 223.0, 'adi': 'KALAY IV SİYANÜR'},
    {'simgesi': 'Pb(CN)2', 'mol agir': 259.0, 'adi': 'KURŞUN II SİYANÜR'},
    {'simgesi': 'Pb(CN)4', 'mol agir': 311.0, 'adi': 'KURŞUN IV SİYANÜR'},
    {'simgesi': 'NaCNO', 'mol agir': 65.0, 'adi': 'SODYUM SİYANAT'},
    {'simgesi': 'KCNO', 'mol agir': 81.0, 'adi': 'POTASYUM SİYANAT'},
    {'simgesi': 'NH4CNO', 'mol agir': 60.0, 'adi': 'AMONYUM SİYANAT'},
    {'simgesi': 'AgCNO', 'mol agir': 150.0, 'adi': 'GÜMÜŞ SİYANAT'},
    {'simgesi': 'Ca(CNO)2', 'mol agir': 124.0, 'adi': 'KALSİYUM SİYANAT'},
    {'simgesi': 'LiNO3', 'mol agir': 69.0, 'adi': 'LİTYUM NİTRAT'},
    {'simgesi': 'NaNO3', 'mol agir': 85.0, 'adi': 'SODYUM NİTRAT'},
    {'simgesi': 'KNO3', 'mol agir': 101.0, 'adi': 'POTASYUM NİTRAT'},
    {'simgesi': 'AgNO3', 'mol agir': 170.0, 'adi': 'GÜMÜŞ NİTRAT'},
    {'simgesi': 'NH4NO3', 'mol agir': 80.0, 'adi': 'AMONYUM NİTRAT'},
    {'simgesi': 'Be(NO3)2', 'mol agir': 133.0, 'adi': 'BERİLYUM NİTRAT'},
    {'simgesi': 'Mg(NO3)2', 'mol agir': 148.0, 'adi': 'MAGNEZYUM NİTRAT'},
    {'simgesi': 'Ca(NO3)2', 'mol agir': 164.0, 'adi': 'KALSİYUM NİTRAT'},
    {'simgesi': 'Sr(NO3)2', 'mol agir': 212.0, 'adi': 'STRONSİYUM NİTRAT'},
    {'simgesi': 'Ba(NO3)2', 'mol agir': 261.0, 'adi': 'BARYUM NİTRAT'},
    {'simgesi': 'Zn(NO3)2', 'mol agir': 189.0, 'adi': 'ÇİNKO NİTRAT'},
    {'simgesi': 'Al(NO3)3', 'mol agir': 213.0, 'adi': 'ALÜMİNYUM NİTRAT'},
    {'simgesi': 'CuNO3', 'mol agir': 125.5, 'adi': 'BAKIR I NİTRAT'},
    {'simgesi': 'Cu(NO3)2', 'mol agir': 187.5, 'adi': 'BAKIR II NİTRAT'},
    {'simgesi': 'HgNO3', 'mol agir': 262.0, 'adi': 'CIVA I NİTRAT'},
    {'simgesi': 'Hg(NO3)2', 'mol agir': 324.0, 'adi': 'CIVA II NİTRAT'},
    {'simgesi': 'Fe(NO3)2', 'mol agir': 180.0, 'adi': 'DEMİR II NİTRAT'},
    {'simgesi': 'Fe(NO3)3', 'mol agir': 242.0, 'adi': 'DEMİR III NİTRAT'},
    {'simgesi': 'Mn(NO3)2', 'mol agir': 179.0, 'adi': 'MANGAN II NİTRAT'},
    {'simgesi': 'Mn(NO3)4', 'mol agir': 303.0, 'adi': 'MANGAN IV NİTRAT'},
    {'simgesi': 'Sn(NO3)2', 'mol agir': 243.0, 'adi': 'KALAY II NİTRAT'},
    {'simgesi': 'Sn(NO3)4', 'mol agir': 367.0, 'adi': 'KALAY IV NİTRAT'},
    {'simgesi': 'Pb(NO3)2', 'mol agir': 331.0, 'adi': 'KURŞUN II NİTRAT'},
    {'simgesi': 'Pb(NO3)4', 'mol agir': 455.0, 'adi': 'KURŞUN IV NİTRAT'},
    {'simgesi': 'LiClO3', 'mol agir': 90.5, 'adi': 'LİTYUM KLORAT'},
    {'simgesi': 'NaClO3', 'mol agir': 106.5, 'adi': 'SODYUM KLORAT'},
    {'simgesi': 'KClO3', 'mol agir': 122.5, 'adi': 'POTASYUM KLORAT'},
    {'simgesi': 'AgClO3', 'mol agir': 191.5, 'adi': 'GÜMÜŞ KLORAT'},
    {'simgesi': 'NH4ClO3', 'mol agir': 101.5, 'adi': 'AMONYUM KLORAT'},
    {'simgesi': 'Be(ClO3)2', 'mol agir': 176.0, 'adi': 'BERİLYUM KLORAT'},
    {'simgesi': 'Mg(ClO3)2', 'mol agir': 191.0, 'adi': 'MAGNEZYUM KLORAT'},
    {'simgesi': 'Ca(ClO3)2', 'mol agir': 207.0, 'adi': 'KALSİYUM KLORAT'},
    {'simgesi': 'Sr(ClO3)2', 'mol agir': 255.0, 'adi': 'STRONSİYUM KLORAT'},
    {'simgesi': 'Ba(ClO3)2', 'mol agir': 304.0, 'adi': 'BARYUM KLORAT'},
    {'simgesi': 'Zn(ClO3)2', 'mol agir': 232.0, 'adi': 'ÇİNKO KLORAT'},
    {'simgesi': 'Al(ClO3)3', 'mol agir': 277.5, 'adi': 'ALÜMİNYUM KLORAT'},
    {'simgesi': 'CuClO3', 'mol agir': 147.0, 'adi': 'BAKIR I KLORAT'},
    {'simgesi': 'Cu(ClO3)2', 'mol agir': 230.5, 'adi': 'BAKIR II KLORAT'},
    {'simgesi': 'HgClO3', 'mol agir': 283.5, 'adi': 'CIVA I KLORAT'},
    {'simgesi': 'Hg(ClO3)2', 'mol agir': 367.0, 'adi': 'CIVA II KLORAT'},
    {'simgesi': 'Fe(ClO3)2', 'mol agir': 223.0, 'adi': 'DEMİR II KLORAT'},
    {'simgesi': 'Fe(ClO3)3', 'mol agir': 306.5, 'adi': 'DEMİR III KLORAT'},
    {'simgesi': 'Mn(ClO3)2', 'mol agir': 222.0, 'adi': 'MANGAN II KLORAT'},
    {'simgesi': 'Mn(ClO3)4', 'mol agir': 389.0, 'adi': 'MANGAN IV KLORAT'},
    {'simgesi': 'Sn(ClO3)2', 'mol agir': 286.0, 'adi': 'KALAY II KLORAT'},
    {'simgesi': 'Sn(ClO3)4', 'mol agir': 453.0, 'adi': 'KALAY IV KLORAT'},
    {'simgesi': 'Pb(ClO3)2', 'mol agir': 374.0, 'adi': 'KURŞUN II KLORAT'},
    {'simgesi': 'Pb(ClO3)4', 'mol agir': 541.0, 'adi': 'KURŞUN IV KLORAT'},
    {'simgesi': 'LİBrO3', 'mol agir': 135.0, 'adi': 'LİTYUM BROMAT'},
    {'simgesi': 'NaBrO3', 'mol agir': 151.0, 'adi': 'SODYUM BROMAT'},
    {'simgesi': 'KBrO3', 'mol agir': 167.0, 'adi': 'POTASYUM BROMAT'},
    {'simgesi': 'AgBrO3', 'mol agir': 236.0, 'adi': 'GÜMÜŞ BROMAT'},
    {'simgesi': 'NH4BrO3', 'mol agir': 146.0, 'adi': 'AMONYUM BROMAT'},
    {'simgesi': 'Be(BrO3)2', 'mol agir': 265.0, 'adi': 'BERİLYUM BROMAT'},
    {'simgesi': 'Mg(BrO3)2', 'mol agir': 280.0, 'adi': 'MAGNEZYUM BROMAT'},
    {'simgesi': 'Ca(BrO3)2', 'mol agir': 296.0, 'adi': 'KALSİYUM BROMAT'},
    {'simgesi': 'Sr(BrO3)2', 'mol agir': 344.0, 'adi': 'STRONSİYUM BROMAT'},
    {'simgesi': 'Ba(BrO3)2', 'mol agir': 393.0, 'adi': 'BARYUM BROMAT'},
    {'simgesi': 'Zn(BrO3)2', 'mol agir': 321.0, 'adi': 'ÇİNKO BROMAT'},
    {'simgesi': 'Al(BrO3)3', 'mol agir': 411.0, 'adi': 'ALÜMİNYUM BROMAT'},
    {'simgesi': 'CuBrO3', 'mol agir': 191.5, 'adi': 'BAKIR I BROMAT'},
    {'simgesi': 'Cu(BrO3)2', 'mol agir': 319.5, 'adi': 'BAKIR II BROMAT'},
    {'simgesi': 'HgBrO3', 'mol agir': 328.0, 'adi': 'CIVA I BROMAT'},
    {'simgesi': 'Hg(BrO3)2', 'mol agir': 456.0, 'adi': 'CIVA II BROMAT'},
    {'simgesi': 'Fe(BrO3)2', 'mol agir': 312.0, 'adi': 'DEMİR II BROMAT'},
    {'simgesi': 'Fe(BrO3)3', 'mol agir': 440.0, 'adi': 'DEMİR III BROMAT'},
    {'simgesi': 'Mn(BrO3)2', 'mol agir': 311.0, 'adi': 'MANGAN II BROMAT'},
    {'simgesi': 'Mn(BrO3)4', 'mol agir': 567.0, 'adi': 'MANGAN IV BROMAT'},
    {'simgesi': 'Sn(BrO3)2', 'mol agir': 375.0, 'adi': 'KALAY II BROMAT'},
    {'simgesi': 'Sn(BrO3)4', 'mol agir': 631.0, 'adi': 'KALAY IV BROMAT'},
    {'simgesi': 'Pb(BrO3)2', 'mol agir': 463.0, 'adi': 'KURŞUN II BROMAT'},
    {'simgesi': 'Pb(BrO3)4', 'mol agir': 719.0, 'adi': 'KURŞUN IV BROMAT'},
    {'simgesi': 'LiIO3', 'mol agir': 182.0, 'adi': 'LİTYUM İYODAT'},
    {'simgesi': 'NaIO3', 'mol agir': 198.0, 'adi': 'SODYUM İYODAT'},
    {'simgesi': 'KIO3', 'mol agir': 214.0, 'adi': 'POTASYUM İYODAT'},
    {'simgesi': 'AgIO3', 'mol agir': 283.0, 'adi': 'GÜMÜŞ İYODAT'},
    {'simgesi': 'NH4IO3', 'mol agir': 193.0, 'adi': 'AMONYUM İYODAT'},
    {'simgesi': 'Be(IO3)2', 'mol agir': 359.0, 'adi': 'BERİLYUM İYODAT'},
    {'simgesi': 'Mg(IO3)2', 'mol agir': 374.0, 'adi': 'MAGNEZYUM İYODAT'},
    {'simgesi': 'Ca(IO3)2', 'mol agir': 390.0, 'adi': 'KALSİYUM İYODAT'},
    {'simgesi': 'Sr(IO3)2', 'mol agir': 438.0, 'adi': 'STRONSİYUM İYODAT'},
    {'simgesi': 'Ba(IO3)2', 'mol agir': 487.0, 'adi': 'BARYUM İYODAT'},
    {'simgesi': 'Zn(IO3)2', 'mol agir': 415.0, 'adi': 'ÇİNKO İYODAT'},
    {'simgesi': 'Al(IO3)3', 'mol agir': 552.0, 'adi': 'ALÜMİNYUM İYODAT'},
    {'simgesi': 'CuIO3', 'mol agir': 238.5, 'adi': 'BAKIR I İYODAT'},
    {'simgesi': 'Cu(IO3)2', 'mol agir': 413.5, 'adi': 'BAKIR II İYODAT'},
    {'simgesi': 'HgIO3', 'mol agir': 375.0, 'adi': 'CIVA I İYODAT'},
    {'simgesi': 'Hg(IO3)2', 'mol agir': 550.0, 'adi': 'CIVA II İYODAT'},
    {'simgesi': 'Fe(IO3)2', 'mol agir': 406.0, 'adi': 'DEMİR II İYODAT'},
    {'simgesi': 'Fe(IO3)3', 'mol agir': 581.0, 'adi': 'DEMİR III İYODAT'},
    {'simgesi': 'Mn(IO3)2', 'mol agir': 405.0, 'adi': 'MANGAN II İYODAT'},
    {'simgesi': 'Mn(IO3)4', 'mol agir': 755.0, 'adi': 'MANGAN IV İYODAT'},
    {'simgesi': 'Sn(IO3)2', 'mol agir': 469.0, 'adi': 'KALAY II İYODAT'},
    {'simgesi': 'Sn(IO3)4', 'mol agir': 819.0, 'adi': 'KALAY IV İYODAT'},
    {'simgesi': 'Pb(IO3)2', 'mol agir': 557.0, 'adi': 'KURŞUN II İYODAT'},
    {'simgesi': 'Pb(IO3)4', 'mol agir': 907.0, 'adi': 'KURŞUN IV İYODAT'},
    {'simgesi': 'LiMnO4', 'mol agir': 126.0, 'adi': 'LİTYUM PERMANGANAT'},
    {'simgesi': 'NaMnO4', 'mol agir': 142.0, 'adi': 'SODYUM PERMANGANAT'},
    {'simgesi': 'KMnO4', 'mol agir': 158.0, 'adi': 'POTASYUM PERMANGANAT'},
    {'simgesi': 'AgMnO4', 'mol agir': 227.0, 'adi': 'GÜMÜŞ PERMANGANAT'},
    {'simgesi': 'NH4MnO4', 'mol agir': 137.0, 'adi': 'AMONYUM PERMANGANAT'},
    {'simgesi': 'Be(MnO4)2', 'mol agir': 247.0, 'adi': 'BERİLYUM PERMANGANAT'},
    {'simgesi': 'Mg(MnO4)2', 'mol agir': 262.0, 'adi': 'MAGNEZYUM PERMANGANAT'},
    {'simgesi': 'Ca(MnO4)2', 'mol agir': 278.0, 'adi': 'KALSİYUM PERMANGANAT'},
    {'simgesi': 'Sr(MnO4)2', 'mol agir': 326.0, 'adi': 'STRONSİYUM PERMANGANAT'},
    {'simgesi': 'Ba(MnO4)2', 'mol agir': 375.0, 'adi': 'BARYUM PERMANGANAT'},
    {'simgesi': 'Zn(MnO4)2', 'mol agir': 303.0, 'adi': 'ÇİNKO PERMANGANAT'},
    {'simgesi': 'Al(MnO4)3', 'mol agir': 384.0, 'adi': 'ALÜMİNYUM PERMANGANAT'},
    {'simgesi': 'CuMnO4', 'mol agir': 182.5, 'adi': 'BAKIR I PERMANGANAT'},
    {'simgesi': 'Cu(MnO4)2', 'mol agir': 301.5, 'adi': 'BAKIR II PERMANGANAT'},
    {'simgesi': 'HgMnO4', 'mol agir': 319.0, 'adi': 'CIVA I PERMANGANAT'},
    {'simgesi': 'Hg(MnO4)2', 'mol agir': 438.0, 'adi': 'CIVA II PERMANGANAT'},
    {'simgesi': 'Fe(MnO4)2', 'mol agir': 294.0, 'adi': 'DEMİR II PERMANGANAT'},
    {'simgesi': 'Fe(MnO4)3', 'mol agir': 413.0, 'adi': 'DEMİR III PERMANGANAT'},
    {'simgesi': 'Mn(MnO4)2', 'mol agir': 293.0, 'adi': 'MANGAN II PERMANGANAT'},
    {'simgesi': 'Mn(MnO4)4', 'mol agir': 531.0, 'adi': 'MANGAN IV PERMANGANAT'},
    {'simgesi': 'Sn(MnO4)2', 'mol agir': 357.0, 'adi': 'KALAY II PERMANGANAT'},
    {'simgesi': 'Sn(MnO4)4', 'mol agir': 595.0, 'adi': 'KALAY IV PERMANGANAT'},
    {'simgesi': 'Pb(MnO4)2', 'mol agir': 445.0, 'adi': 'KURŞUN II PERMANGANAT'},
    {'simgesi': 'Pb(MnO4)4', 'mol agir': 683.0, 'adi': 'KURŞUN IV PERMANGANAT'},
    {'simgesi': 'Li2MnO4', 'mol agir': 133.0, 'adi': 'LİTYUM MANGANAT'},
    {'simgesi': 'Na2MnO4', 'mol agir': 165.0, 'adi': 'SODYUM MANGANAT'},
    {'simgesi': 'K2MnO4', 'mol agir': 197.0, 'adi': 'POTASYUM MANGANAT'},
    {'simgesi': 'Ag2MnO4', 'mol agir': 335.0, 'adi': 'GÜMÜŞ MANGANAT'},
    {'simgesi': '(NH4)2MnO4', 'mol agir': 155.0, 'adi': 'AMONYUM MANGANAT'},
    {'simgesi': 'BeMnO4', 'mol agir': 128.0, 'adi': 'BERİLYUM MANGANAT'},
    {'simgesi': 'MgMnO4', 'mol agir': 143.0, 'adi': 'MAGNEZYUM MANGANAT'},
    {'simgesi': 'CaMnO4', 'mol agir': 159.0, 'adi': 'KALSİYUM MANGANAT'},
    {'simgesi': 'SrMnO4', 'mol agir': 207.0, 'adi': 'STRONSİYUM MANGANAT'},
    {'simgesi': 'BaMnO4', 'mol agir': 256.0, 'adi': 'BARYUM MANGANAT'},
    {'simgesi': 'ZnMnO4', 'mol agir': 184.0, 'adi': 'ÇİNKO MANGANAT'},
    {'simgesi': 'Al2(MnO4)3', 'mol agir': 411.0, 'adi': 'ALÜMİNYUM MANGANAT'},
    {'simgesi': 'Cu2MnO4', 'mol agir': 246.0, 'adi': 'BAKIR I MANGANAT'},
    {'simgesi': 'CuMnO4', 'mol agir': 182.5, 'adi': 'BAKIR II MANGANAT'},
    {'simgesi': 'Hg2MnO4', 'mol agir': 519.0, 'adi': 'CIVA I MANGANAT'},
    {'simgesi': 'HgMnO4', 'mol agir': 319.0, 'adi': 'CIVA II MANGANAT'},
    {'simgesi': 'FeMnO4', 'mol agir': 175.0, 'adi': 'DEMİR II MANGANAT'},
    {'simgesi': 'Fe2(MnO4)3', 'mol agir': 469.0, 'adi': 'DEMİR III MANGANAT'},
    {'simgesi': 'MnMnO4', 'mol agir': 174.0, 'adi': 'MANGAN II MANGANAT'},
    {'simgesi': 'Mn(MnO4)2', 'mol agir': 293.0, 'adi': 'MANGAN IV MANGANAT'},
    {'simgesi': 'SnMnO4', 'mol agir': 238.0, 'adi': 'KALAY II MANGANAT'},
    {'simgesi': 'Sn(MnO4)2', 'mol agir': 357.0, 'adi': 'KALAY IV MANGANAT'},
    {'simgesi': 'PbMnO4', 'mol agir': 326.0, 'adi': 'KURŞUN II MANGANAT'},
    {'simgesi': 'Pb(MnO4)2', 'mol agir': 445.0, 'adi': 'KURŞUN IV MANGANAT'},
    {'simgesi': 'Li2SO3', 'mol agir': 94.0, 'adi': 'LİTYUM SÜLFİT'},
    {'simgesi': 'Na2SO3', 'mol agir': 126.0, 'adi': 'SODYUM SÜLFİT'},
    {'simgesi': 'K2SO3', 'mol agir': 158.0, 'adi': 'POTASYUM SÜLFİT'},
    {'simgesi': 'Ag2SO3', 'mol agir': 296.0, 'adi': 'GÜMÜŞ SÜLFİT'},
    {'simgesi': '(NH4)2SO3', 'mol agir': 116.0, 'adi': 'AMONYUM SÜLFİT'},
    {'simgesi': 'BeSO3', 'mol agir': 89.0, 'adi': 'BERİLYUM SÜLFİT'},
    {'simgesi': 'MgSO3', 'mol agir': 104.0, 'adi': 'MAGNEZYUM SÜLFİT'},
    {'simgesi': 'CaSO3', 'mol agir': 120.0, 'adi': 'KALSİYUM SÜLFİT'},
    {'simgesi': 'SrSO3', 'mol agir': 168.0, 'adi': 'STRONSİYUM SÜLFİT'},
    {'simgesi': 'BaSO3', 'mol agir': 217.0, 'adi': 'BARYUM SÜLFİT'},
    {'simgesi': 'ZnSO3', 'mol agir': 145.0, 'adi': 'ÇİNKO SÜLFİT'},
    {'simgesi': 'Al2(SO3)3', 'mol agir': 294.0, 'adi': 'ALÜMİNYUM SÜLFİT'},
    {'simgesi': 'Cu2SO3', 'mol agir': 207.0, 'adi': 'BAKIR I SÜLFİT'},
    {'simgesi': 'CuSO3', 'mol agir': 143.5, 'adi': 'BAKIR II SÜLFİT'},
    {'simgesi': 'Hg2SO3', 'mol agir': 480.0, 'adi': 'CIVA I SÜLFİT'},
    {'simgesi': 'HgSO3', 'mol agir': 280.0, 'adi': 'CIVA II SÜLFİT'},
    {'simgesi': 'FeSO3', 'mol agir': 136.0, 'adi': 'DEMİR II SÜLFİT'},
    {'simgesi': 'Fe2(SO3)3', 'mol agir': 352.0, 'adi': 'DEMİR III SÜLFİT'},
    {'simgesi': 'MnSO3', 'mol agir': 135.0, 'adi': 'MANGAN II SÜLFİT'},
    {'simgesi': 'Mn(SO3)2', 'mol agir': 215.0, 'adi': 'MANGAN IV SÜLFİT'},
    {'simgesi': 'SnSO3', 'mol agir': 199.0, 'adi': 'KALAY II SÜLFİT'},
    {'simgesi': 'Sn(SO3)2', 'mol agir': 279.0, 'adi': 'KALAY IV SÜLFİT'},
    {'simgesi': 'PbSO3', 'mol agir': 287.0, 'adi': 'KURŞUN II SÜLFİT'},
    {'simgesi': 'Pb(SO3)2', 'mol agir': 367.0, 'adi': 'KURŞUN IV SÜLFİT'},
    {'simgesi': 'Lİ2SO4', 'mol agir': 110.0, 'adi': 'LİTYUM SÜLFAT'},
    {'simgesi': 'Na2SO4', 'mol agir': 142.0, 'adi': 'SODYUM SÜLFAT'},
    {'simgesi': 'K2SO4', 'mol agir': 174.0, 'adi': 'POTASYUM SÜLFAT'},
    {'simgesi': 'Ag2SO4', 'mol agir': 312.0, 'adi': 'GÜMÜŞ SÜLFAT'},
    {'simgesi': '(NH4)2SO4', 'mol agir': 132.0, 'adi': 'AMONYUM SÜLFAT'},
    {'simgesi': 'BeSO4', 'mol agir': 105.0, 'adi': 'BERİLYUM SÜLFAT'},
    {'simgesi': 'MgSO4', 'mol agir': 120.0, 'adi': 'MAGNEZYUM SÜLFAT'},
    {'simgesi': 'CaSO4', 'mol agir': 136.0, 'adi': 'KALSİYUM SÜLFAT'},
    {'simgesi': 'SrSO4', 'mol agir': 184.0, 'adi': 'STRONSİYUM SÜLFAT'},
    {'simgesi': 'BaSO4', 'mol agir': 233.0, 'adi': 'BARYUM SÜLFAT'},
    {'simgesi': 'ZnSO4', 'mol agir': 161.0, 'adi': 'ÇİNKO SÜLFAT'},
    {'simgesi': 'Al2(SO4)3', 'mol agir': 342.0, 'adi': 'ALÜMİNYUM SÜLFAT'},
    {'simgesi': 'Cu2SO4', 'mol agir': 223.0, 'adi': 'BAKIR I SÜLFAT'},
    {'simgesi': 'CuSO4', 'mol agir': 159.5, 'adi': 'BAKIR II SÜLFAT'},
    {'simgesi': 'Hg2SO4', 'mol agir': 496.0, 'adi': 'CIVA I SÜLFAT'},
    {'simgesi': 'HgSO4', 'mol agir': 296.0, 'adi': 'CIVA II SÜLFAT'},
    {'simgesi': 'FeSO4', 'mol agir': 152.0, 'adi': 'DEMİR II SÜLFAT'},
    {'simgesi': 'Fe2(SO4)3', 'mol agir': 400.0, 'adi': 'DEMİR III SÜLFAT'},
    {'simgesi': 'MnSO4', 'mol agir': 151.0, 'adi': 'MANGAN II SÜLFAT'},
    {'simgesi': 'Mn(SO4)2', 'mol agir': 247.0, 'adi': 'MANGAN IV SÜLFAT'},
    {'simgesi': 'SnSO4', 'mol agir': 215.0, 'adi': 'KALAY II SÜLFAT'},
    {'simgesi': 'Sn(SO4)2', 'mol agir': 311.0, 'adi': 'KALAY IV SÜLFAT'},
    {'simgesi': 'PbSO4', 'mol agir': 303.0, 'adi': 'KURŞUN II SÜLFAT'},
    {'simgesi': 'Pb(SO4)2', 'mol agir': 399.0, 'adi': 'KURŞUN IV SÜLFAT'},
    {'simgesi': 'Li2CO3', 'mol agir': 74.0, 'adi': 'LİTYUM KARBONAT'},
    {'simgesi': 'Na2CO3', 'mol agir': 106.0, 'adi': 'SODYUM KARBONAT/ÇAMAŞIR SODASI'},
    {'simgesi': 'NaHCO3', 'mol agir': 84.0, 'adi': 'SODYUM BİKARBONAT/YEMEK SODASI'},
    {'simgesi': 'K2CO3', 'mol agir': 138.0, 'adi': 'POTASYUM KARBONAT'},
    {'simgesi': 'KHCO3', 'mol agir': 100.0, 'adi': 'POTASYUM BİKARBONAT'},
    {'simgesi': 'Ag2CO3', 'mol agir': 276.0, 'adi': 'GÜMÜŞ KARBONAT'},
    {'simgesi': '(NH4)2CO3', 'mol agir': 96.0, 'adi': 'AMONYUM KARBONAT'},
    {'simgesi': 'BeCO3', 'mol agir': 69.0, 'adi': 'BERİLYUM KARBONAT'},
    {'simgesi': 'MgCO3', 'mol agir': 84.0, 'adi': 'MAGNEZYUM KARBONAT'},
    {'simgesi': 'CaCO3', 'mol agir': 100.0, 'adi': 'KALSİYUM KARBONAT'},
    {'simgesi': 'SrCO3', 'mol agir': 148.0, 'adi': 'STRONSİYUM KARBONAT'},
    {'simgesi': 'BaCO3', 'mol agir': 197.0, 'adi': 'BARYUM KARBONAT'},
    {'simgesi': 'Al2(CO3)3', 'mol agir': 234.0, 'adi': 'ALÜMİNYUM KARBONAT'},
    {'simgesi': 'ZnCO3', 'mol agir': 125.0, 'adi': 'ÇİNKO KARBONAT'},
    {'simgesi': 'Cu2CO3', 'mol agir': 187.0, 'adi': 'BAKIR I KARBONAT'},
    {'simgesi': 'CuCO3', 'mol agir': 123.5, 'adi': 'BAKIR II KARBONAT'},
    {'simgesi': 'Hg2CO3', 'mol agir': 460.0, 'adi': 'CIVA I KARBONAT'},
    {'simgesi': 'HgCO3', 'mol agir': 260.0, 'adi': 'CIVA II KARBONAT'},
    {'simgesi': 'FeCO3', 'mol agir': 116.0, 'adi': 'DEMİR II KARBONAT'},
    {'simgesi': 'Fe2(CO3)3', 'mol agir': 292.0, 'adi': 'DEMİR III KARBONAT'},
    {'simgesi': 'MnCO3', 'mol agir': 115.0, 'adi': 'MANGAN II KARBONAT'},
    {'simgesi': 'Mn(CO3)2', 'mol agir': 175.0, 'adi': 'MANGAN IV KARBONAT'},
    {'simgesi': 'SnCO3', 'mol agir': 179.0, 'adi': 'KALAY II KARBONAT'},
    {'simgesi': 'Sn(CO3)2', 'mol agir': 239.0, 'adi': 'KALAY IV KARBONAT'},
    {'simgesi': 'PbCO3', 'mol agir': 267.0, 'adi': 'KURŞUN II KARBONAT'},
    {'simgesi': 'Pb(CO3)2', 'mol agir': 327.0, 'adi': 'KURŞUN IV KARBONAT'},
    {'simgesi': 'Li3PO4', 'mol agir': 116.0, 'adi': 'LİTYUM FOSFAT'},
    {'simgesi': 'Na3PO4', 'mol agir': 164.0, 'adi': 'SODYUM FOSFAT'},
    {'simgesi': 'K3PO4', 'mol agir': 212.0, 'adi': 'POTASYUM FOSFAT'},
    {'simgesi': 'Ag3PO4', 'mol agir': 419.0, 'adi': 'GÜMÜŞ FOSFAT'},
    {'simgesi': '(NH4)3PO4', 'mol agir': 150.0, 'adi': 'AMONYUM FOSFAT'},
    {'simgesi': 'Be3(PO4)2', 'mol agir': 217.0, 'adi': 'BERİLYUM FOSFAT'},
    {'simgesi': 'Mg3(PO4)2', 'mol agir': 262.0, 'adi': 'MAGNEZYUM FOSFAT'},
    {'simgesi': 'Ca3(PO4)2', 'mol agir': 310.0, 'adi': 'KALSİYUM FOSFAT'},
    {'simgesi': 'Sr3(PO4)2', 'mol agir': 454.0, 'adi': 'STRONSİYUM FOSFAT'},
    {'simgesi': 'Ba3(PO4)2', 'mol agir': 601.0, 'adi': 'BARYUM FOSFAT'},
    {'simgesi': 'Zn3(PO4)2', 'mol agir': 385.0, 'adi': 'ÇİNKO FOSFAT'},
    {'simgesi': 'AlPO4', 'mol agir': 122.0, 'adi': 'ALÜMİNYUM FOSFAT'},
    {'simgesi': 'Cu3PO4', 'mol agir': 285.5, 'adi': 'BAKIR I FOSFAT'},
    {'simgesi': 'Cu3(PO4)2', 'mol agir': 380.5, 'adi': 'BAKIR II FOSFAT'},
    {'simgesi': 'Hg3PO4', 'mol agir': 695.0, 'adi': 'CIVA I FOSFAT'},
    {'simgesi': 'Hg3(PO4)2', 'mol agir': 790.0, 'adi': 'CIVA II FOSFAT'},
    {'simgesi': 'Fe3(PO4)2', 'mol agir': 358.0, 'adi': 'DEMİR II FOSFAT'},
    {'simgesi': 'FePO4', 'mol agir': 151.0, 'adi': 'DEMİR III FOSFAT'},
    {'simgesi': 'Mn3(PO4)2', 'mol agir': 355.0, 'adi': 'MANGAN II FOSFAT'},
    {'simgesi': 'Mn3(PO4)4', 'mol agir': 545.0, 'adi': 'MANGAN IV FOSFAT'},
    {'simgesi': 'Sn3(PO4)2', 'mol agir': 547.0, 'adi': 'KALAY II FOSFAT'},
    {'simgesi': 'Sn3(PO4)4', 'mol agir': 737.0, 'adi': 'KALAY IV FOSFAT'},
    {'simgesi': 'Pb3(PO4)2', 'mol agir': 811.0, 'adi': 'KURŞUN II FOSFAT'},
    {'simgesi': 'Pb3(PO4)4', 'mol agir': 1001.0, 'adi': 'KURŞUN IV FOSFAT'},
    {'simgesi': 'LiCH3COO', 'mol agir': 66.0, 'adi': 'LİTYUM ASETAT'},
    {'simgesi': 'NaCH3COO', 'mol agir': 82.0, 'adi': 'SODYUM ASETAT'},
    {'simgesi': 'KCH3COO', 'mol agir': 98.0, 'adi': 'POTASYUM ASETAT'},
    {'simgesi': 'AgCH3COO', 'mol agir': 167.0, 'adi': 'GÜMÜŞ ASETAT'},
    {'simgesi': 'NH4CH3COO', 'mol agir': 77.0, 'adi': 'AMONYUM ASETAT'},
    {'simgesi': 'Be(CH3COO)2', 'mol agir': 127.0, 'adi': 'BERİLYUM ASETAT'},
    {'simgesi': 'Mg(CH3COO)2', 'mol agir': 142.0, 'adi': 'MAGNEZYUM ASETAT'},
    {'simgesi': 'Ca(CH3COO)2', 'mol agir': 158.0, 'adi': 'KALSİYUM ASETAT'},
    {'simgesi': 'Sr(CH3COO)2', 'mol agir': 206.0, 'adi': 'STRONSİYUM ASETAT'},
    {'simgesi': 'Ba(CH3COO)2', 'mol agir': 255.0, 'adi': 'BARYUM ASETAT'},
    {'simgesi': 'Zn(CH3COO)2', 'mol agir': 183.0, 'adi': 'ÇİNKO ASETAT'},
    {'simgesi': 'Al(CH3COO)3', 'mol agir': 204.0, 'adi': 'ALÜMİNYUM ASETAT'},
    {'simgesi': 'CuCH3COO', 'mol agir': 122.5, 'adi': 'BAKIR I ASETAT'},
    {'simgesi': 'Cu(CH3COO)2', 'mol agir': 181.5, 'adi': 'BAKIR II ASETAT'},
    {'simgesi': 'HgCH3COO', 'mol agir': 259.0, 'adi': 'CIVA I ASETAT'},
    {'simgesi': 'Hg(CH3COO)2', 'mol agir': 318.0, 'adi': 'CIVA II ASETAT'},
    {'simgesi': 'Fe(CH3COO)2', 'mol agir': 174.0, 'adi': 'DEMİR II ASETAT'},
    {'simgesi': 'Fe(CH3COO)3', 'mol agir': 233.0, 'adi': 'DEMİR III ASETAT'},
    {'simgesi': 'Mn(CH3COO)2', 'mol agir': 173.0, 'adi': 'MANGAN II ASETAT'},
    {'simgesi': 'Mn(CH3COO)4', 'mol agir': 291.0, 'adi': 'MANGAN IV ASETAT'},
    {'simgesi': 'Sn(CH3COO)2', 'mol agir': 237.0, 'adi': 'KALAY II ASETAT'},
    {'simgesi': 'Sn(CH3COO)4', 'mol agir': 355.0, 'adi': 'KALAY IV ASETAT'},
    {'simgesi': 'Pb(CH3COO)2', 'mol agir': 325.0, 'adi': 'KURŞUN II ASETAT'},
    {'simgesi': 'Pb(CH3COO)4', 'mol agir': 443.0, 'adi': 'KURŞUN IV ASETAT'},
    {'simgesi': 'Lİ2C2O4', 'mol agir': 102.0, 'adi': 'LİTYUM OKZALAT'},
    {'simgesi': 'Na2C2O4', 'mol agir': 134.0, 'adi': 'SODYUM OKZALAT'},
    {'simgesi': 'K2C2O4', 'mol agir': 166.0, 'adi': 'POTASYUM OKZALAT'},
    {'simgesi': 'Ag2C2O4', 'mol agir': 304.0, 'adi': 'GÜMÜŞ OKZALAT'},
    {'simgesi': '(NH4)2C2O4', 'mol agir': 124.0, 'adi': 'AMONYUM OKZALAT'},
    {'simgesi': 'BeC2O4', 'mol agir': 97.0, 'adi': 'BERİLYUM OKZALAT'},
    {'simgesi': 'MgC2O4', 'mol agir': 112.0, 'adi': 'MAGNEZYUM OKZALAT'},
    {'simgesi': 'CaC2O4', 'mol agir': 128.0, 'adi': 'KALSİYUM OKZALAT'},
    {'simgesi': 'SrC2O4', 'mol agir': 176.0, 'adi': 'STRONSİYUM OKZALAT'},
    {'simgesi': 'BaC2O4', 'mol agir': 225.0, 'adi': 'BARYUM OKZALAT'},
    {'simgesi': 'ZnC2O4', 'mol agir': 153.0, 'adi': 'ÇİNKO OKZALAT'},
    {'simgesi': 'Al2(C2O4)3', 'mol agir': 318.0, 'adi': 'ALÜMİNYUM OKZALAT'},
    {'simgesi': 'Cu2C2O4', 'mol agir': 215.0, 'adi': 'BAKIR I OKZALAT'},
    {'simgesi': 'CuC2O4', 'mol agir': 151.5, 'adi': 'BAKIR II OKZALAT'},
    {'simgesi': 'Hg2C2O4', 'mol agir': 288.0, 'adi': 'CIVA I OKZALAT'},
    {'simgesi': 'HgC2O4', 'mol agir': 488.0, 'adi': 'CIVA II OKZALAT'},
    {'simgesi': 'FeC2O4', 'mol agir': 144.0, 'adi': 'DEMİR II OKZALAT'},
    {'simgesi': 'Fe2(C2O4)3', 'mol agir': 376.0, 'adi': 'DEMİR III OKZALAT'},
    {'simgesi': 'MnC2O4', 'mol agir': 143.0, 'adi': 'MANGAN II OKZALAT'},
    {'simgesi': 'Mn(C2O4)2', 'mol agir': 231.0, 'adi': 'MANGAN IV OKZALAT'},
    {'simgesi': 'SnC2O4', 'mol agir': 207.0, 'adi': 'KALAY II OKZALAT'},
    {'simgesi': 'Sn(C2O4)2', 'mol agir': 295.0, 'adi': 'KALAY IV OKZALAT'},
    {'simgesi': 'PbC2O4', 'mol agir': 295.0, 'adi': 'KURŞUN II OKZALAT'},
    {'simgesi': 'Pb(C2O4)2', 'mol agir': 383.0, 'adi': 'KURŞUN IV OKZALAT'},
    {'simgesi': 'Lİ2CrO4', 'mol agir': 130.0, 'adi': 'LİTYUM KROMAT'},
    {'simgesi': 'Na2CrO4', 'mol agir': 162.0, 'adi': 'SODYUM KROMAT'},
    {'simgesi': 'K2CrO4', 'mol agir': 194.0, 'adi': 'POTASYUM KROMAT'},
    {'simgesi': 'Ag2CrO4', 'mol agir': 332.0, 'adi': 'GÜMÜŞ KROMAT'},
    {'simgesi': '(NH4)2CrO4', 'mol agir': 152.0, 'adi': 'AMONYUM KROMAT'},
    {'simgesi': 'BeCrO4', 'mol agir': 125.0, 'adi': 'BERİLYUM KROMAT'},
    {'simgesi': 'MgCrO4', 'mol agir': 140.0, 'adi': 'MAGNEZYUM KROMAT'},
    {'simgesi': 'CaCrO4', 'mol agir': 156.0, 'adi': 'KALSİYUM KROMAT'},
    {'simgesi': 'SrCrO4', 'mol agir': 204.0, 'adi': 'STRONSİYUM KROMAT'},
    {'simgesi': 'BaCrO4', 'mol agir': 253.0, 'adi': 'BARYUM KROMAT'},
    {'simgesi': 'ZnCrO4', 'mol agir': 181.0, 'adi': 'ÇİNKO KROMAT'},
    {'simgesi': 'Al2(CrO4)3', 'mol agir': 402.0, 'adi': 'ALÜMİNYUM KROMAT'},
    {'simgesi': 'Cu2CrO4', 'mol agir': 243.0, 'adi': 'BAKIR I KROMAT'},
    {'simgesi': 'CuCrO4', 'mol agir': 179.5, 'adi': 'BAKIR II KROMAT'},
    {'simgesi': 'Hg2CrO4', 'mol agir': 516.0, 'adi': 'CIVA I KROMAT'},
    {'simgesi': 'HgCrO4', 'mol agir': 316.0, 'adi': 'CIVA II KROMAT'},
    {'simgesi': 'FeCrO4', 'mol agir': 172.0, 'adi': 'DEMİR II KROMAT'},
    {'simgesi': 'Fe2(CrO4)3', 'mol agir': 460.0, 'adi': 'DEMİR III KROMAT'},
    {'simgesi': 'MnCrO4', 'mol agir': 171.0, 'adi': 'MANGAN II KROMAT'},
    {'simgesi': 'Mn(CrO4)2', 'mol agir': 287.0, 'adi': 'MANGAN IV KROMAT'},
    {'simgesi': 'SnCrO4', 'mol agir': 235.0, 'adi': 'KALAY II KROMAT'},
    {'simgesi': 'Sn(CrO4)2', 'mol agir': 351.0, 'adi': 'KALAY IV KROMAT'},
    {'simgesi': 'PbCrO4', 'mol agir': 323.0, 'adi': 'KURŞUN II KROMAT'},
    {'simgesi': 'Pb(CrO4)2', 'mol agir': 439.0, 'adi': 'KURŞUN IV KROMAT'},
    {'simgesi': 'Lİ2Cr2O7', 'mol agir': 230.0, 'adi': 'LİTYUM DİKROMAT'},
    {'simgesi': 'Na2Cr2O7', 'mol agir': 262.0, 'adi': 'SODYUM DİKROMAT'},
    {'simgesi': 'K2Cr2O7', 'mol agir': 294.0, 'adi': 'POTASYUM DİKROMAT'},
    {'simgesi': 'Ag2Cr2O7', 'mol agir': 432.0, 'adi': 'GÜMÜŞ DİKROMAT'},
    {'simgesi': '(NH4)2Cr2O7', 'mol agir': 252.0, 'adi': 'AMONYUM DİKROMAT'},
    {'simgesi': 'BeCr2O7', 'mol agir': 225.0, 'adi': 'BERİLYUM DİKROMAT'},
    {'simgesi': 'MgCr2O7', 'mol agir': 240.0, 'adi': 'MAGNEZYUM DİKROMAT'},
    {'simgesi': 'CaCr2O7', 'mol agir': 256.0, 'adi': 'KALSİYUM DİKROMAT'},
    {'simgesi': 'SrCr2O7', 'mol agir': 304.0, 'adi': 'STRONSİYUM DİKROMAT'},
    {'simgesi': 'BaCr2O7', 'mol agir': 353.0, 'adi': 'BARYUM DİKROMAT'},
    {'simgesi': 'ZnCr2O7', 'mol agir': 281.0, 'adi': 'ÇİNKO DİKROMAT'},
    {'simgesi': 'Al2(Cr2O7)3', 'mol agir': 702.0, 'adi': 'ALÜMİNYUM DİKROMAT'},
    {'simgesi': 'Cu2Cr2O7', 'mol agir': 343.0, 'adi': 'BAKIR I DİKROMAT'},
    {'simgesi': 'CuCr2O7', 'mol agir': 279.5, 'adi': 'BAKIR II DİKROMAT'},
    {'simgesi': 'Hg2Cr2O7', 'mol agir': 616.0, 'adi': 'CIVA I DİKROMAT'},
    {'simgesi': 'HgCr2O7', 'mol agir': 416.0, 'adi': 'CIVA II DİKROMAT'},
    {'simgesi': 'FeCr2O7', 'mol agir': 272.0, 'adi': 'DEMİR II DİKROMAT'},
    {'simgesi': 'Fe2(Cr2O7)3', 'mol agir': 760.0, 'adi': 'DEMİR III DİKROMAT'},
    {'simgesi': 'MnCr2O7', 'mol agir': 271.0, 'adi': 'MANGAN II DİKROMAT'},
    {'simgesi': 'Mn(Cr2O7)2', 'mol agir': 487.0, 'adi': 'MANGAN IV DİKROMAT'},
    {'simgesi': 'SnCr2O7', 'mol agir': 335.0, 'adi': 'KALAY II DİKROMAT'},
    {'simgesi': 'Sn(Cr2O7)2', 'mol agir': 551.0, 'adi': 'KALAY IV DİKROMAT'},
    {'simgesi': 'PbCr2O7', 'mol agir': 423.0, 'adi': 'KURŞUN II DİKROMAT'},
    {'simgesi': 'Pb(Cr2O7)2', 'mol agir': 639.0, 'adi': 'KURŞUN IV DİKROMAT'},
    {'simgesi': 'CaC2', 'mol agir': 64.0, 'adi': 'KALSİYUM KARBÜR'},
    {'simgesi': 'Al4C3', 'mol agir': 144.0, 'adi': 'ALÜMİNYUM KARBÜR'},
    {'simgesi': 'HCHO', 'mol agir': 30.0, 'adi': 'FORMALDEHİT/METANAL'},
    {'simgesi': 'HCOOH', 'mol agir': 46.0, 'adi': 'FORMİK ASİT/KARINCA ASİTİ/METANOİK ASİT'},
    {'simgesi': 'CH3COOH', 'mol agir': 60.0, 'adi': 'ASETİK ASİT/SİRKE ASİTİ/ETANOİK ASİT'},
    {'simgesi': 'CH3OH', 'mol agir': 32.0, 'adi': 'METANOL/METİL ALKOL'},
    {'simgesi': 'C2H5OH', 'mol agir': 46.0, 'adi': 'ETANOL/ETİL ALKOL'},
    {'simgesi': 'HNO2', 'mol agir': 47.0, 'adi': 'NİTRÖZ ASİT'},
    {'simgesi': 'HNO3', 'mol agir': 63.0, 'adi': 'NİTRİK ASİT/KEZZAP'},
    {'simgesi': 'HCN', 'mol agir': 27.0, 'adi': 'HİDROSİYANİK ASİT/SİYANÜR ASİTİ'},
    {'simgesi': 'HClO', 'mol agir': 52.5, 'adi': 'HİPOKLORİK ASİT'},
    {'simgesi': 'HClO2', 'mol agir': 68.5, 'adi': 'KLORÖZ ASİTİ'},
    {'simgesi': 'HClO3', 'mol agir': 84.5, 'adi': 'KLORİK ASİT'},
    {'simgesi': 'HClO4', 'mol agir': 100.5, 'adi': 'PERKLORİK ASİT'},
    {'simgesi': 'HBrO3', 'mol agir': 129.0, 'adi': 'BROMİK ASİT'},
    {'simgesi': 'HMnO4', 'mol agir': 120.0, 'adi': 'PERMANGANİK ASİT'},
    {'simgesi': 'H2MnO4', 'mol agir': 121.0, 'adi': 'MANGANİK ASİT'},
    {'simgesi': 'H2SO3', 'mol agir': 82.0, 'adi': 'SÜLFÜROZ ASİT'},
    {'simgesi': 'H2SO4', 'mol agir': 98.0, 'adi': 'SÜLFÜRİK ASİT/ZAC YAĞI'},
    {'simgesi': 'H3PO3', 'mol agir': 82.0, 'adi': 'FOSFORÖZ ASİT'},
    {'simgesi': 'H3PO4', 'mol agir': 98.0, 'adi': 'FOSFORİK ASİT'},
    {'simgesi': 'H2CO3', 'mol agir': 62.0, 'adi': 'KARBONİK ASİT'},
    {'simgesi': 'H2C2O4', 'mol agir': 90.0, 'adi': 'OKZALİK ASİT'},
    {'simgesi': 'H2CrO4', 'mol agir': 118.0, 'adi': 'KROMİK ASİT'},
    {'simgesi': 'H2Cr2O7', 'mol agir': 218.0, 'adi': 'DİKROMİK ASİT'},
    {'simgesi': 'Na2SiO3', 'mol agir': 122.0, 'adi': 'SODYUM SİLİKAT'},
    {'simgesi': 'K2SiO3', 'mol agir': 154.0, 'adi': 'POTASYUM SİLİKAT'},
    {'simgesi': 'CaSiO3', 'mol agir': 116.0, 'adi': 'KALSİYUM SİLİKAT'},
    {'simgesi': 'MgSiO3', 'mol agir': 100.0, 'adi': 'MAGNEZYUM SİLİKAT'},
    {'simgesi': 'FeSiO3', 'mol agir': 132.0, 'adi': 'DEMİR SİLİKAT'},
    {'simgesi': 'NaAlSiO4', 'mol agir': 126.0, 'adi': 'SODYUM ALÜMİNYUM SİLİKAT'},
    {'simgesi': 'KAlSiO4', 'mol agir': 142.0, 'adi': 'POTASYUM ALÜMİNYUM SİLİKAT'},
    {'simgesi': 'Ca2SiO4', 'mol agir': 172.0, 'adi': 'KALSİYUM METASİLİKAT'},
    {'simgesi': 'Mg2SiO4', 'mol agir': 140.0, 'adi': 'MAGNEZYUM METASİLİKAT'},
    {'simgesi': 'NaFeSiO4', 'mol agir': 171.0, 'adi': 'SODYUM FERRİSİLİKAT'},
    {'simgesi': 'KFeSiO4', 'mol agir': 187.0, 'adi': 'POTASYUM FERRİSİLİKAT'},
    {'simgesi': 'Fe2SiO4', 'mol agir': 204.0, 'adi': 'DEMİR SİLİKAT'},
    {'simgesi': 'Na2Al2O4', 'mol agir': 164.0, 'adi': 'SODYUM ALÜMİNAT'},
    {'simgesi': 'CaAl2O4', 'mol agir': 158.0, 'adi': 'KALSİYUM ALÜMİNAT'},
    {'simgesi': 'Al2O3.2SiO2.2H2O', 'mol agir': 258.0, 'adi': 'KİL/KAOLİN'}
]

# --- 2. YARDIMCI FONKSİYONLAR (Aynen Koruyoruz) ---
def tr_lower(metin):
    if not metin: return ""
    duzeltme = str.maketrans("İIĞÜŞÖÇ", "iığüşöç")
    return str(metin).translate(duzeltme).lower()


def alt_simge_yap(metin):
    if not metin: return ""
    alt_simgeler = str.maketrans("0123456789", "₀₁₂₃₄₅₆₇₈₉")
    return str(metin).translate(alt_simgeler)


# --- 3. STREAMLIT ARAYÜZÜ ---
st.set_page_config(page_title="Kimya Asistan v1.5.0", page_icon="🧪")

# Başlık
st.title("🧪 Kimya Asistan v1.5.0")

# İmza (Sağ tarafa veya alt satıra şık bir yazı)
st.caption("by kimyabdullah | [İletişim](https://github.com/abdullahyildirimer)")

st.write("Formül veya isim yazarak sorgulayın.")

# Öneri Listesi Hazırlığı (Tkinter'deki tum_isimler kısmı)
tum_isimler = [b["simgesi"] for b in bilesikler] + [b["adi"] for b in bilesikler]

# MOBİL AVANTAJI: Tkinter'deki Listbox yerine 'selectbox' veya 'selectbox' benzeri bir arama kutusu
# Streamlit'in kendi "searchable" (aranabilir) kutusu otomatik öneri sunar.
giris = st.selectbox(
    "Formül veya İsim Seçin/Yazın:",
    options=[""] + sorted(list(set(tum_isimler))),
    format_func=lambda x: "Seçiniz..." if x == "" else x
)

# Sorgulama Butonu
if st.button("SORGULA", use_container_width=True):
    if giris != "":
        aranan = tr_lower(giris)
        sonuc = None

        # Senin yazdığın o manuel arama döngüsü:
        for b in bilesikler:
            temiz_simge = tr_lower(b['simgesi']).replace('\xa0', '').strip()
            temiz_ad = tr_lower(b['adi']).replace('\xa0', '').strip()

            if aranan == temiz_simge or aranan == temiz_ad:
                sonuc = b
                break

        if sonuc:
            # Görsel sonuçları kartlar içinde gösteriyoruz
            st.markdown(f"<h1 style='text-align: center; color: #283593;'>{alt_simge_yap(sonuc['simgesi'])}</h1>",
                        unsafe_allow_html=True)

            col1, col2 = st.columns(2)
            with col1:
                st.info(f"**BİLEŞİK ADI:**\n\n{sonuc['adi']}")
            with col2:
                st.success(f"**MOLEKÜL/FORMÜL AĞIRLIĞI:**\n\n{sonuc['mol agir']} g/mol")
        else:
            st.error("Bileşik bulunamadı.")
    else:
        st.warning("Lütfen bir giriş yapın.")

st.markdown("---")
st.markdown("<p style='text-align: right; color: gray;'>by kimyabdullah</p>", unsafe_allow_html=True)
